'use strict';
(()=>{
const D=window.COURSE_DATA,S=window.CourseStore,main=document.getElementById('main');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,href,secondary=false)=>`<a class="course-button ${secondary?'secondary':''}" href="${href}">${label}</a>`;
const point=id=>D.points.find(p=>p.id===id),question=id=>D.questions.find(q=>q.id===id);
let active=null,warning='';
function heading(kicker,title,description){return `<div class="course-heading"><div><div class="eyebrow-course">${kicker}</div><h1>${title}</h1><p>${description}</p></div></div>`;}
function home(){const s=S.read();return heading('Course materials','LifeScience 11','Open a lesson, explore the diagrams, then check what you know.')+`<div class="home-layout"><div>${D.topics.map((topic,i)=>{const group=D.units.filter(x=>x.topic===i);return `<section class="unit-group"><div class="unit-heading"><span class="unit-number">${String(i+1).padStart(2,'0')}</span><h2>${esc(topic)}</h2></div>${group.length?group.map(u=>card(u,s)).join(''):'<div class="pending-material"><span>Course materials coming soon</span><span>Pending</span></div>'}</section>`;}).join('')}</div><aside class="study-side"><div class="eyebrow-course">Check your understanding</div><h2 style="margin-top:12px">Ready to review the course?</h2><p>The combined test checks all ${D.uniquePointCount} learning objectives with ${D.questions.length} questions. You can pause and resume in this browser.</p>${button('Start / resume combined test','#test/all')}<a class="side-secondary" href="#review/all">Review your mistakes (${Object.values(s.answers).filter(a=>!a.correct).length})</a><div class="home-interactive"><h2>Learn by doing</h2><p>Build a timeline, match cell structures, follow a protein and explore three more activities.</p>${button('Explore interactive activities','units/biology/index.html#activities')}</div><hr class="side-rule"><div class="extra-side"><p><strong>${D.units.length} lessons available</strong><br>${D.uniquePointCount} learning objectives<br>${D.questions.length} scored questions<br>2 image discussions</p><a class="side-secondary" href="#knowledge">Open knowledge checklist</a><p style="font-size:12px;margin-top:20px">The original Concept 1 source is still needed to verify its page references.</p></div></aside></div>`;}
function card(u,s){const points=D.points.filter(p=>p.unit===u.id),done=points.filter(p=>s.read[p.id]).length;return `<article class="material-card"><div class="card-image"><img src="${u.image}" alt="${esc(u.imageAlt||u.title)}"></div><div class="card-body"><div class="card-type">Interactive lesson</div><a class="card-title" href="${u.href}">${esc(u.title)}</a><p>${esc(u.description)}</p><div class="card-meta"><span>${u.pointCount} objectives${u.verified?'':' · source check pending'}</span><span>${u.questionCount} questions</span><span>${done}/${points.length} studied</span></div><div class="card-progress" aria-label="${done} of ${points.length} objectives marked studied"><span style="width:${done/points.length*100}%"></span></div></div></article>`;}
function knowledge(){const s=S.read();return heading('Learning checklist',`${D.uniquePointCount} learning objectives`,'Mark objectives as studied in each lesson. Practise any objective here, or take the full unit test.')+`<p class="muted">${D.countingRule}</p>${D.units.map(u=>`<section class="knowledge-group"><div class="unit-heading"><h2>${esc(u.title)}</h2></div><p class="muted">${u.pointCount} objectives · ${u.questionCount} scored questions${u.verified?' · PDF verified':' · original source verification pending'}</p><div class="course-actions">${button('Open lesson',u.href)}${button('Unit test',`#test/${u.id}`,true)}${button('Practise unit',`#practice/${u.id}`,true)}</div>${D.points.filter(p=>p.unit===u.id).map(p=>`<div class="knowledge-row"><span class="knowledge-status">${s.read[p.id]?'✓ Studied':'○ To study'}</span><a class="knowledge-link" href="${p.href}">${esc(p.title)}<small>${p.id} · ${p.verified?'PDF':'Source reference'} p. ${p.pages}</small></a>${button('Practise',`#practice/${u.id}/${p.key}`,true)}</div>`).join('')}</section>`).join('')}`;}
function shuffle(arr){const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function routeInfo(){const parts=location.hash.slice(1).split('/');const mode=parts[0],unit=parts[1]||'all';let pool=D.questions;
if(mode==='review'){const answers=S.read().answers;pool=pool.filter(q=>answers[q.id]&&!answers[q.id].correct&&(unit==='all'||q.unit===unit));}
else if(unit==='question'){pool=pool.filter(q=>q.id===parts[2]);}
else{if(unit!=='all')pool=pool.filter(q=>q.unit===unit);if(parts[2])pool=pool.filter(q=>q.points.includes(unit+'-'+parts[2]));}
const p=parts[2]&&point(unit+'-'+parts[2]);const title=mode==='review'?'Review mistakes':unit==='question'?'Question practice':p?p.title:unit==='all'?'Combined test':D.units.find(u=>u.id===unit)?.title||'Practice';
return {mode,unit,pool,title,key:parts.join('/')};}
function persistSession(){if(active)S.update(s=>{s.sessions[active.key]=active.session;});}
function start(info,reset=false){if(!info.pool.length){render();return;}let sess=S.read().sessions[info.key];const currentIds=info.pool.map(q=>q.id);const valid=sess&&sess.version===D.version&&Array.isArray(sess.ids)&&sess.ids.length===currentIds.length&&sess.ids.every(id=>currentIds.includes(id))&&typeof sess.answers==='object'&&sess.answers&&Number.isInteger(sess.index)&&sess.index>=0&&sess.index<sess.ids.length;
if(!valid&&!reset&&info.mode==='test'&&sess?.version===D.version&&Array.isArray(sess.ids)&&sess.answers&&typeof sess.answers==='object'){
 const oldIds=sess.ids.filter(id=>currentIds.includes(id)),ids=[...oldIds,...shuffle(currentIds.filter(id=>!oldIds.includes(id)))];
 const answers=Object.fromEntries(Object.entries(sess.answers).filter(([id,a])=>ids.includes(id)&&Number.isInteger(a)&&a>=0&&a<question(id).options.length));
 sess={version:D.version,ids,answers,checked:{},index:Math.max(0,ids.findIndex(id=>answers[id]===undefined)),submitted:false};warning='This test includes updated course material. Your previous answers have been kept.';
}else if(!valid||reset){sess={version:D.version,ids:shuffle(info.pool.map(q=>q.id)),answers:{},checked:{},index:0,submitted:false};}
active={...info,session:sess};persistSession();renderQuiz();}
function feedback(q,selected){const ok=selected===q.answer;return `<div class="feedback-panel ${ok?'':'incorrect'}" role="status"><strong>${ok?'Correct':'Correct answer: '+esc(q.options[q.answer])}</strong><p>${esc(q.explanation)}</p>${q.points.map(id=>{const p=point(id);return `<a href="${p.href}">Review ${esc(p.title)}</a>`;}).join(' · ')}</div>`;}
function renderIntro(info){const saved=S.read().sessions[info.key];return `<div class="test-shell">${heading(info.mode==='test'?'Assessment':'Practice',esc(info.title),info.mode==='test'?'Answer all questions. Your score and explanations appear after you submit.':'Check each answer immediately, then use the explanation to review the lesson.')}<section class="test-intro"><h2>${info.pool.length} questions</h2><p>${info.mode==='test'?'This test includes every scored question in the selected lessons. Each question is worth one point. You may change answers before submitting.':'Questions you miss remain in your mistake list until you answer them correctly in practice or a test.'}</p>${info.unit==='all'?'<p>The two ambiguous image exercises are available in the Levels lesson as discussions and are excluded from scoring.</p>':''}<p class="muted">Saved only in this browser on this device. No account is required.</p>${saved?`<p>You have a saved ${saved.submitted?'result':'attempt'} (${Object.keys(saved.answers||{}).length}/${saved.ids.length} answered).</p>`:''}<div class="course-actions"><button class="primary" data-start>${saved?'Resume / view result':'Start'}</button>${saved?'<button class="course-button secondary" data-restart>Start a new attempt</button>':''}${button('Course materials','#home',true)}</div></section></div>`;}
function renderQuiz(){const {session:s}=active;if(s.submitted){renderResult();return;}const q=question(s.ids[s.index]),selected=s.answers[q.id],checked=!!s.checked[q.id],practice=active.mode!=='test';const done=Object.keys(s.answers).length;
main.innerHTML=`<div class="test-shell"><div class="eyebrow-course">${practice?'Practice':'Assessment'} · ${esc(active.title)}</div><div class="test-stats"><strong>Question ${s.index+1} of ${s.ids.length}</strong><span>${done}/${s.ids.length} answered · saved in this browser</span></div><div class="test-progress"><span style="width:${done/s.ids.length*100}%"></span></div><section class="question-panel"><span class="eyebrow-course">${esc(D.units.find(u=>u.id===q.unit)?.title||q.unit)} · Source p. ${q.pages}</span><h2 id="question-heading" tabindex="-1">${esc(q.stem)}</h2>${q.image?`<img class="question-image" src="${q.image}" alt="${esc(q.imageAlt)}">`:''}<fieldset class="quiz-options" aria-labelledby="question-heading"><legend class="sr-only">Choose one answer</legend>${q.options.map((o,i)=>`<label class="quiz-option ${checked&&i===q.answer?'correct':checked&&i===selected?'incorrect':''}"><input type="radio" name="answer" value="${i}" ${selected===i?'checked':''} ${checked?'disabled':''}><span>${esc(o)}</span></label>`).join('')}</fieldset>${practice?`<div class="course-actions"><button class="primary" data-check ${selected===undefined||checked?'disabled':''}>Check answer</button>${checked?'<button class="course-button secondary" data-try>Try this question again</button>':''}</div>`:''}${checked?feedback(q,selected):''}${warning?`<p role="alert" class="notice">${esc(warning)}</p>`:''}<div class="test-controls"><button class="course-button secondary" data-prev ${s.index===0?'disabled':''}>Previous</button><button class="course-button secondary" data-next ${s.index===s.ids.length-1?'disabled':''}>Next</button><button class="primary" data-submit>${practice?'Finish practice':'Submit test'}</button></div></section><details><summary>Jump to a question (${done}/${s.ids.length} answered)</summary><div class="question-picker">${s.ids.map((id,i)=>`<button class="${s.answers[id]!==undefined?'answered':''}" aria-label="Question ${i+1}, ${s.answers[id]!==undefined?'answered':'unanswered'}" aria-current="${i===s.index}" data-jump="${i}">${i+1}</button>`).join('')}</div></details><div class="course-actions">${button('Save & return to course','#home',true)}</div></div>`;
bindQuiz();}
function bindQuiz(){const s=active.session,q=question(s.ids[s.index]);main.querySelectorAll('input[name=answer]').forEach(el=>el.onchange=()=>{s.answers[q.id]=Number(el.value);delete s.checked[q.id];warning='';persistSession();renderQuiz();main.querySelector(`input[value="${el.value}"]`).focus();});
const bind=(attr,fn)=>{const e=main.querySelector(`[${attr}]`);if(e)e.onclick=fn;};
const move=i=>{s.index=i;warning='';persistSession();renderQuiz();main.querySelector('#question-heading')?.focus();};
bind('data-prev',()=>move(s.index-1));bind('data-next',()=>move(s.index+1));main.querySelectorAll('[data-jump]').forEach(el=>el.onclick=()=>move(Number(el.dataset.jump)));
bind('data-check',()=>{s.checked[q.id]=true;S.record([q],s.answers,'practice');persistSession();renderQuiz();});
bind('data-try',()=>{delete s.checked[q.id];delete s.answers[q.id];persistSession();renderQuiz();});
bind('data-submit',()=>{const missing=s.ids.findIndex(id=>s.answers[id]===undefined);if(missing>=0){s.index=missing;warning='Answer every question before submitting. This is the first unanswered question.';persistSession();renderQuiz();main.querySelector('#question-heading')?.focus();return;}s.submitted=true;S.record(s.ids.map(question),s.answers,active.mode);persistSession();renderResult();main.focus();});}
function renderResult(){const s=active.session,qs=s.ids.map(question),result=S.grade(qs,s.answers);main.innerHTML=`<div class="test-shell">${heading('Results',esc(active.title),'Review the explanations and return to any learning objective you want to strengthen.')}<section class="results-panel"><div class="score-big">${result.correct} / ${result.total}</div><p>${Math.round(result.correct/result.total*100)}% correct · ${result.total-result.correct} to review</p><div class="course-actions">${button('Review mistakes',`#review/${active.unit==='question'?'all':active.unit}`)}${button('Knowledge checklist','#knowledge',true)}<button class="course-button secondary" data-again>New attempt</button></div>${qs.map((q,i)=>`<details class="result-row"><summary><span class="result-label ${result.rows[i].correct?'':'wrong'}">${result.rows[i].correct?'Correct':'Review'}</span>${i+1}. ${esc(q.stem)}</summary>${q.image?`<img class="question-image" src="${q.image}" alt="${esc(q.imageAlt)}">`:''}<p>Your answer: ${esc(q.options[s.answers[q.id]])}</p>${feedback(q,s.answers[q.id])}</details>`).join('')}</section></div>`;main.querySelector('[data-again]').onclick=()=>start(routeInfo(),true);window.scrollTo(0,0);}
function render(){active=null;warning='';const page=location.hash.slice(1).split('/')[0]||'home';document.querySelectorAll('.course-bar nav a').forEach(a=>{if(a.hash===location.hash||(page==='home'&&a.hash==='#home'))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(page==='home'){main.innerHTML=home();}else if(page==='knowledge'){main.innerHTML=knowledge();}else if(['test','practice','review'].includes(page)){const info=routeInfo();if(!info.pool.length){main.innerHTML=heading('Practice',esc(info.title),'')+`<section class="empty-state"><h2>${page==='review'?'No mistakes to review':'No questions found'}</h2><p>${page==='review'?'Any questions you miss in practice or a test will appear here.':'Open the checklist to choose a learning objective.'}</p>${button('Knowledge checklist','#knowledge')}</section>`;}else{main.innerHTML=renderIntro(info);main.querySelector('[data-start]').onclick=()=>start(info);main.querySelector('[data-restart]')?.addEventListener('click',()=>start(info,true));}}else{main.innerHTML=heading('LifeScience 11','Page not found','Choose a lesson from the course materials.')+button('Course materials','#home');}document.title=(page==='home'?'Course materials':page==='knowledge'?'Knowledge checklist':'Practice & tests')+' · LifeScience 11';S.read();window.scrollTo(0,0);}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(a&&a.hash===location.hash&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey){e.preventDefault();render();}});
window.addEventListener('hashchange',render);window.addEventListener('storage',()=>{if(!active)render();});render();
})();
