const state={view:'explore',level:0,type:'plant',lang:'en',quizMode:'photo',quizIndex:0,photoAnswers:{},conceptAnswers:{},finished:false,quizPool:null};
const remembered=CourseStore.read().legacy?.levels;if(remembered){for(const key of ['lang','quizMode','quizIndex','photoAnswers','conceptAnswers','finished','quizPool'])if(Object.hasOwn(remembered,key))state[key]=remembered[key];}
if(['en','zh','both'].includes(CourseStore.read().language))state.lang=CourseStore.read().language;
const main=document.getElementById('main');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(zh,en)=>`<span class="zh">${zh}</span><span class="en">${en}</span>`;
const bi=(zh,en,cls='')=>`<div class="bilingual-text ${cls}"><p class="zh">${zh}</p><p class="en" lang="en">${en}</p></div>`;
const label=(zh,en)=>state.lang==='en'?en:zh;
function render(){
 document.body.className='course-unit '+(state.lang==='zh'?'zh-only':state.lang==='en'?'en-only':'');
 document.documentElement.lang=state.lang==='en'?'en':'zh-CN';
 document.getElementById('navigation').innerHTML=[['explore','层级探索','Explore'],['practice','看图练习','Practice'],['notes','双语笔记','Notes']].map((v,i)=>`<a href="#${v[0]}" class="${state.view===v[0]?'active':''}" ${state.view===v[0]?'aria-current="page"':''}><span class="nav-number">0${i+1}</span>${label(v[1],v[2])}</a>`).join('');
 document.getElementById('footer-copy').textContent=label('基于原始 PDF · 52 页 · 中英双语学习','Based on the original 52-page PDF · Bilingual learning');
 if(state.view==='explore')renderExplore();else if(state.view==='notes')renderNotes();else renderPractice();
}
function heading(zh,en,descZh,descEn){return `<div class="page-heading"><div><div class="eyebrow">BIOLOGY / ${label('生物学','LEARNING STUDIO')}</div><h1>${t(zh,en)}</h1>${bi(descZh,descEn,'page-subtitle')}</div><a class="pdf-link" href="source.pdf" target="_blank" rel="noopener">${label('查看原始 PDF ↗','Original PDF ↗')}</a></div>`}
function diagram(l){let inner='';if(l.id==='cell')inner='<div class="diagram-graphic"><span class="diagram-node"></span></div>';else if(['tissue','population'].includes(l.id))inner='<div class="diagram-graphic">'+Array(5).fill('<span class="diagram-node"></span>').join('')+'</div>';else inner='<div class="diagram-graphic">'+Array.from({length:5},(_,i)=>`<span class="diagram-node ${i>2?'other':''}"></span>`).join('')+'</div>';return `<div class="mini-diagram" role="img" aria-label="${esc(label(l.tagZh,l.tagEn))}">${inner}<div class="diagram-box">${t(l.tagZh,l.tagEn)}</div>${l.id==='ecosystem'?'<div class="diagram-plus">＋</div><div class="diagram-box">'+t('水 · 空气 · 光 · 土壤','Water · air · light · soil')+'</div>':''}</div>`}
function renderExplore(){const l=LEVELS[state.level];const pic=PHOTO_ITEMS.find(p=>p.page===l[state.type+'Pic']);
 main.innerHTML=heading('从细胞，到整个生态系统','From cell to ecosystem','选择一个层级，看看生命如何由小到大组织起来。','Choose a level to explore how life is organized, from small to large.')+
 `<div class="explorer"><aside class="level-list" aria-label="${label('组织层级','Levels of organization')}"><div class="list-caption">${label('从小到大 / SMALL → LARGE','SMALL → LARGE')}</div>${LEVELS.map((x,i)=>`<button class="level-btn ${state.level===i?'selected':''} ${i===5?'break':''}" data-level="${i}" aria-pressed="${state.level===i}"><span class="num">0${i+1}</span><span><strong class="zh">${x.zh}</strong><span class="en" lang="en">${x.en}</span></span><span class="chevron" aria-hidden="true">›</span></button>`).join('')}</aside>
 <section class="detail-card" aria-labelledby="level-title"><div class="detail-top"><span class="badge">${label('层级','LEVEL')} 0${state.level+1} / 08</span>${state.level<5?`<div class="segmented" aria-label="${label('例子类型','Example type')}"><button data-type="plant" class="${state.type==='plant'?'active':''}" aria-pressed="${state.type==='plant'}">${label('植物','Plants')}</button><button data-type="animal" class="${state.type==='animal'?'active':''}" aria-pressed="${state.type==='animal'}">${label('动物','Animals')}</button></div>`:''}<a class="page-ref" href="source.pdf#page=${l.page}" target="_blank" rel="noopener">PDF p. ${l.page}</a></div>
 <div class="detail-body"><div class="detail-copy"><div class="definition-label">${label('认识这一层级','MEET THIS LEVEL')}</div><h2 id="level-title" class="zh">${l.zh}</h2><p class="en" lang="en">${l.en}</p>${bi(l.defZh,l.defEn,'definition')}${bi(l.keyZh,l.keyEn,'key')}</div><div class="media-panel">${pic?`<div class="image-stage"><img src="images/${pic.image}" alt="${esc(label(pic.subjectZh,pic.subjectEn))}"></div><div class="media-caption">${t(pic.subjectZh,pic.subjectEn)}<p class="page-ref">${label('原图','Original image')} · PDF p. ${pic.page}</p></div>`:diagram(l)}</div></div>
 <div class="examples"><div class="example-strip"><h3>${label('常见例子','EXAMPLES')}</h3>${bi(l.exampleZh||l[state.type+'Zh'],l.exampleEn||l[state.type+'En'])}</div></div><div class="connection"><span class="arrow" aria-hidden="true">↗</span>${bi(l.connectZh,l.connectEn)}${state.level<7?`<button data-next-level aria-label="${label('下一个层级','Next level')}">→</button>`:''}</div></section></div>
 <div class="learning-note">${bi('学习提醒：细胞 → 组织 → 器官 → 器官系统 → 生物体，这条链适用于具有这些结构的多细胞生物。单细胞生物没有组织和器官。','Study note: the cell → tissue → organ → organ system → organism chain applies to multicellular organisms with these structures. Single-celled organisms do not have tissues or organs.')}</div>`;
 main.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{state.level=Number(b.dataset.level);renderExplore();main.querySelector(`[data-level="${state.level}"]`).focus({preventScroll:true})});
 main.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{state.type=b.dataset.type;renderExplore();main.querySelector(`[data-type="${state.type}"]`).focus({preventScroll:true})});
 main.querySelector('[data-next-level]')?.addEventListener('click',()=>{state.level++;renderExplore()});
}
function renderNotes(){main.innerHTML=heading('把概念，真正分清','Understand the distinctions','每个定义都有对应翻译。先理解组成关系，再记忆英文术语。','Compare each definition with its translation. Understand the relationships before memorizing the terms.')+
 `<div class="notes-callout"><h2>${label('一个贯穿全课的问题','ONE QUESTION TO KEEP ASKING')}</h2>${bi('这里是一个细胞、一群细胞、不同组织的组合，还是多个器官的协作？','Am I looking at one cell, a group of cells, different tissues combined, or several organs working together?')}</div><div class="note-grid">`+
 LEVELS.map(l=>`<article class="note-card"><a class="note-meta" href="source.pdf#page=${l.page}" target="_blank" rel="noopener">PDF p. ${l.page} ↗</a><h2>${t(l.zh,' '+l.en)}</h2>${bi(l.defZh,l.defEn)}<details><summary>${label('展开例子与记忆提示','Examples and memory cues')}</summary>${bi(l.keyZh,l.keyEn)}${l.exampleZh?bi(l.exampleZh,l.exampleEn):'<h3>'+label('动物','Animals')+'</h3>'+bi(l.animalZh,l.animalEn)+'<h3>'+label('植物','Plants')+'</h3>'+bi(l.plantZh,l.plantEn)}</details></article>`).join('')+
 `</div><section class="pitfalls"><div class="eyebrow">LOOK A LITTLE CLOSER</div><h2>${t('容易混淆的地方','Common mix-ups')}</h2>${bi('以下为帮助理解而补充的说明，区别于 PDF 的原文定义。','These learning notes clarify the material; they are additions to the PDF definitions.')}${PITFALLS.map((p,i)=>`<article class="pitfall"><span>0${i+1}</span><div><h3>${t(p[0],' '+p[1])}</h3>${bi(p[2],p[3])}</div></article>`).join('')}</section>
 <section class="source-notes"><h2>${label('资料与补充参考','Sources and further reading')}</h2>${bi('课程定义与图片来自你提供的《Levels of Organization Notes》。第2–9页为概念，第10–52页为图片题。图片原始出处保留在 PDF 对应页面；第44页未列图片来源。','Definitions and images come from your Levels of Organization Notes PDF: concepts on pages 2–9 and image exercises on pages 10–52. Original image credits remain on the corresponding PDF pages; page 44 gives no image credit.')}<p>${label('概念补充参考：','Concept clarifications: ')}<a href="https://openstax.org/books/biology-2e/pages/1-2-themes-and-concepts-of-biology" target="_blank" rel="noopener">OpenStax · Organization of life</a> · <a href="https://openstax.org/books/biology-2e/pages/30-1-the-plant-body" target="_blank" rel="noopener">The plant body</a> · <a href="https://openstax.org/books/biology-2e/pages/30-2-stems" target="_blank" rel="noopener">Stems</a> · <a href="https://openstax.org/books/biology-2e/pages/7-5-metabolism-without-oxygen" target="_blank" rel="noopener">Metabolism without oxygen</a> · <a href="https://openstax.org/books/biology/pages/22-2-structure-of-prokaryotes" target="_blank" rel="noopener">Prokaryotes</a></p></section>`}
function allQuestions(){return state.quizMode==='photo'?PHOTO_ITEMS:CONCEPTS}
function questionKey(q){return String(q.page&&state.quizMode==='photo'?q.page:q.id)}
function questionPool(){return state.quizPool?allQuestions().filter(q=>state.quizPool.includes(questionKey(q))):allQuestions()}
function answerStore(){return state.quizMode==='photo'?state.photoAnswers:state.conceptAnswers}
function isDiscussion(q){return state.quizMode==='photo'&&[38,50].includes(q.page)}
function rightAnswer(q){return state.quizMode==='photo'?q.level:q.answer}
function quizStats(){const pool=questionPool(),answers=answerStore(),scored=pool.filter(q=>!isDiscussion(q));return {total:pool.length,answered:pool.filter(q=>Object.hasOwn(answers,questionKey(q))).length,scored:scored.length,correct:scored.filter(q=>answers[questionKey(q)]===rightAnswer(q)).length,wrong:scored.filter(q=>Object.hasOwn(answers,questionKey(q))&&answers[questionKey(q)]!==rightAnswer(q)).map(questionKey)}}
function submitAnswer(choice){const pool=questionPool(),q=pool[state.quizIndex],answers=answerStore();if(!q||state.finished)throw Error('No active question');const options=state.quizMode==='photo'?LEVELS.slice(0,5).map(l=>l.id):q.options.map((_,i)=>i);if(!options.includes(choice))throw Error('Invalid answer');if(Object.hasOwn(answers,questionKey(q)))throw Error('Question already answered');answers[questionKey(q)]=choice;const sharedId=state.quizMode==='photo'?'levels-photo-'+q.page:'levels-original-'+q.id;const sharedQuestion=COURSE_DATA.questions.find(item=>item.id===sharedId);if(sharedQuestion){const selected=state.quizMode==='photo'?LEVELS.findIndex(level=>level.id===choice):choice;CourseStore.record([sharedQuestion],{[sharedId]:selected},'legacy-levels');}renderPractice();main.querySelector('.feedback')?.focus({preventScroll:true});return {correct:isDiscussion(q)?null:choice===rightAnswer(q),discussion:isDiscussion(q),sourceAnswer:rightAnswer(q)}}
function resetQuiz(wrongOnly=false){const keys=wrongOnly?quizStats().wrong:null;if(wrongOnly&&!keys.length)return;state.quizPool=keys;if(keys){for(const k of keys)delete answerStore()[k]}else if(state.quizMode==='photo')state.photoAnswers={};else state.conceptAnswers={};state.quizIndex=0;state.finished=false;renderPractice()}
function renderPractice(){
 CourseStore.update(s=>{s.legacy??={};s.legacy.levels={lang:state.lang,quizMode:state.quizMode,quizIndex:state.quizIndex,photoAnswers:state.photoAnswers,conceptAnswers:state.conceptAnswers,finished:state.finished,quizPool:state.quizPool};});
 const pool=questionPool(),stats=quizStats(),q=pool[state.quizIndex],photo=state.quizMode==='photo';
 const head=heading('看见图片，判断层级','Identify the level','先独立判断，再查看原文答案与中英解析。','Make your choice, then compare it with the source answer and bilingual explanation.');
 const tabs=`<div class="practice-toolbar"><div class="tabbar"><button data-mode="photo" class="${photo?'active':''}" aria-pressed="${photo}">${label('原图练习 · 43题','Image practice · 43')}</button><button data-mode="concept" class="${!photo?'active':''}" aria-pressed="${!photo}">${label('概念辨析 · 8题','Concept check · 8')}</button></div><div class="stat">${label('已作答','Answered')} ${stats.answered} / ${stats.total}${state.quizPool?' · '+label('错题重练','Review mistakes'):''}</div></div>`;
 if(state.finished){main.innerHTML=head+tabs+`<section class="quiz-summary"><div class="eyebrow">${label('本轮完成','ROUND COMPLETE')}</div><h2>${label('看看你的掌握情况','How well did you do?')}</h2><div class="score">${stats.correct}<small> / ${stats.scored}</small></div>${bi('答对 '+stats.correct+' 道计分题。'+(photo?'两道有歧义的原图作为辨析题，不计入分数。':''),'You answered '+stats.correct+' scored questions correctly.'+(photo?' Two ambiguous source images are discussion items and are not scored.':''))}<div class="summary-actions">${stats.wrong.length?`<button class="button primary" data-review>${label('重练错题','Review mistakes')} (${stats.wrong.length})</button>`:''}<button class="button" data-restart>${label('重新练习全部题目','Restart all questions')}</button><a class="button" href="#notes">${label('回顾双语笔记','Review notes')}</a></div></section>`;}
 else{
 const answers=answerStore(),key=questionKey(q),done=Object.hasOwn(answers,key),selected=answers[key],correct=rightAnswer(q),discussion=isDiscussion(q),level=photo?LEVELS.find(l=>l.id===q.level):null;
 const opts=photo?LEVELS.slice(0,5).map(l=>({value:l.id,zh:l.zh,en:l.en})):q.options.map((o,i)=>({value:i,zh:o[0],en:o[1]}));
 const hint=photo?PHOTO_HINTS[q.page]:null;
 const explainZh=photo?level.defZh:q.explainZh,explainEn=photo?level.defEn:q.explainEn;
 main.innerHTML=head+tabs+`<div class="tip-line">${photo?label('原图保留教材中的英文标注。先看观察对象；两道有歧义的题仅供辨析，不计分。','Original diagram labels are retained. Focus on the target; two ambiguous images are unscored discussion items.'):label('把定义用到新情境中，不只记住图片。','Apply the definitions to new situations, beyond memorizing pictures.')}</div><div class="quiz-progress" role="progressbar" aria-label="${label('答题进度','Quiz progress')}" aria-valuemin="0" aria-valuemax="${stats.total}" aria-valuenow="${stats.answered}"><span style="width:${stats.answered/stats.total*100}%"></span></div>
 <div class="quiz-layout"><div class="quiz-visual">${photo?`<div class="quiz-image"><img src="images/${q.image}" alt="${esc(label(q.subjectZh,q.subjectEn))}"></div>`:`<div class="concept-art"><span class="big-number" aria-hidden="true">0${state.quizIndex+1}</span>${bi(q.sceneZh,q.sceneEn)}</div>`}<div class="quiz-source">${photo?label('图片来源','Image source'):label('对应概念','Related concepts')} · PDF p. ${q.page}${done?` · <a href="source.pdf#page=${photo?q.page:parseInt(q.page)}" target="_blank" rel="noopener">${label('查看原页 ↗','Source page ↗')}</a>`:''}</div></div>
 <section class="quiz-panel" aria-labelledby="question-title"><div class="eyebrow">${discussion?label('原图辨析 · 不计分','DISCUSSION · UNSCORED'):label('练习','QUESTION')} ${String(state.quizIndex+1).padStart(2,'0')} / ${pool.length}</div><h2 id="question-title">${photo?label('这属于哪个组织层级？','Which level is shown?'):label(q.zh,q.en)}</h2>${!photo&&state.lang==='both'?`<p class="question-translation en" lang="en">${q.en}</p>`:''}${photo?bi(discussion?'先判断你看到的层级，再比较原文的观察目标。':hint?hint[0]:'关注图中主要的结构或完整个体。',discussion?'Choose the level you see, then compare it with the source’s intended target.':hint?hint[1]:'Focus on the main structure or complete individual.'):''}
 <div class="answers ${photo?'':'concept-answers'}" role="group" aria-label="${label('答案选项','Answer choices')}">${opts.map((o,i)=>`<button class="answer ${done&&!discussion&&o.value===correct?'correct':''} ${done&&!discussion&&o.value===selected&&selected!==correct?'wrong':''} ${done&&discussion&&o.value===selected?'chosen':''}" data-answer="${o.value}" ${done?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${state.lang!=='en'?`<span class="zh">${o.zh}</span>`:''}<small class="en" lang="en">${o.en}</small></span>${done&&!discussion&&o.value===correct?'<span class="answer-mark" aria-label="'+label('正确答案','Correct answer')+'">✓</span>':''}${done&&!discussion&&o.value===selected&&selected!==correct?'<span class="answer-mark" aria-label="'+label('你的选择','Your choice')+'">×</span>':''}</button>`).join('')}</div>
 ${done?`<div class="feedback" tabindex="-1" role="status"><h3>${discussion?label('比较观察范围，而不是只背答案','Compare the scope, not just the answer'):selected===correct?label('答对了 · 看看为什么','Correct · Here is why'):label('再分清这两个层级','Let’s distinguish the levels')}</h3>${photo?`<p class="source-answer">${label('原文答案：','Source answer: ')}<strong>${label(q.type==='plant'?'植物':'动物',q.type==='plant'?'Plant':'Animal')} · ${label(level.zh,level.en)}</strong></p>`:''}${bi(explainZh,explainEn)}${photo&&q.noteZh?`<div class="image-note">${bi(q.noteZh,q.noteEn)}</div>`:''}</div>`:''}
 <div class="quiz-controls"><button class="button" data-prev ${state.quizIndex===0?'disabled':''}>← ${label('上一题','Previous')}</button><span class="stat">${stats.correct} ${label('题正确','correct')}</span><button class="button primary" data-next ${!done?'disabled':''}>${state.quizIndex===pool.length-1?label('查看结果','See results'):label('下一题','Next')} →</button></div></section></div>`;
 }
 main.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(state.quizMode===b.dataset.mode)return;state.quizMode=b.dataset.mode;state.quizIndex=0;state.quizPool=null;state.finished=false;renderPractice()});
 main.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>submitAnswer(photo?b.dataset.answer:Number(b.dataset.answer)));
 main.querySelector('[data-prev]')?.addEventListener('click',()=>{state.quizIndex--;renderPractice();main.querySelector('#question-title')?.scrollIntoView({block:'nearest'})});
 main.querySelector('[data-next]')?.addEventListener('click',()=>{if(state.quizIndex===pool.length-1)state.finished=true;else state.quizIndex++;renderPractice();main.querySelector('.quiz-layout,.quiz-summary')?.scrollIntoView({block:'start',behavior:'auto'})});
 main.querySelector('[data-restart]')?.addEventListener('click',()=>resetQuiz());main.querySelector('[data-review]')?.addEventListener('click',()=>resetQuiz(true));
}
document.getElementById('language').value=state.lang;
document.getElementById('language').onchange=e=>{state.lang=e.target.value;CourseStore.update(s=>{s.language=state.lang;s.legacy??={};s.legacy.levels={...(s.legacy.levels||{}),lang:state.lang};});render()};
function applyLessonHash(){const v=location.hash.slice(1);if(v.startsWith('level-')){const i=LEVELS.findIndex(l=>l.id===v.slice(6));state.level=i>=0?i:0;state.view='explore';}else if(v.startsWith('photo-')){state.view='practice';state.quizMode='photo';state.quizPool=null;state.finished=false;state.quizIndex=Math.max(0,PHOTO_ITEMS.findIndex(p=>p.page===Number(v.slice(6))));}else if(['hierarchy','life-processes'].includes(v)){state.view='notes';}else state.view=['explore','practice','notes'].includes(v)?v:'explore';render();}
window.addEventListener('hashchange',applyLessonHash);applyLessonHash();
// Progressive enhancement: the same quiz action is available in supporting browsers.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'read_learning_state',title:'Read learning state',description:'Read the current learning view and quiz progress without revealing unanswered quiz answers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({view:state.view,language:state.lang,level:LEVELS[state.level].id,quizMode:state.quizMode,questionNumber:state.quizIndex+1,finished:state.finished,progress:quizStats()})},{signal:lifecycle.signal})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'submit_quiz_answer',title:'Submit a quiz answer',description:'Submit and grade an answer for the currently visible quiz question. Image answers use a level id; concept answers use a zero-based option index.',inputSchema:{type:'object',properties:{answer:{oneOf:[{type:'string',enum:['cell','tissue','organ','system','organism']},{type:'integer',minimum:0,maximum:2}]}},required:['answer'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(state.view!=='practice'||!input||Object.keys(input).some(k=>k!=='answer'))throw Error('An active quiz and a valid answer are required');return submitAnswer(input.answer)}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
