// Learning additions clarify the supplied PDF; source answers remain unchanged.
LEVELS[3].plantZh='茎叶系统（shoot system，常称地上部系统）、根系（root system）';
LEVELS[3].plantPic=37;
PHOTO_ITEMS.find(p=>p.page===39).noteZh='图中小肠和大肠各自属于器官。原文使用复数 organs；不能只因多个器官出现在一张图中，就把每个器官判作整个系统。';
PHOTO_ITEMS.find(p=>p.page===39).noteEn='The small and large intestines are individual organs. The source uses the plural organs; showing several organs in one picture does not make each one an entire organ system.';
for(const page of [33,48]){const p=PHOTO_ITEMS.find(p=>p.page===page);p.noteZh='';p.noteEn='';}
PHOTO_ITEMS.find(p=>p.page===51).noteZh='图中展示多块肌肉的整体分布，原文将其归为肌肉系统。';
PHOTO_ITEMS.find(p=>p.page===51).noteEn='The diagram shows the distribution of many muscles; the source classifies the group as a muscular system.';
window.CONCEPTS=[
{id:'c1',page:'2–6',zh:'哪个顺序由简单到复杂？',en:'Which order runs from simplest to most complex?',sceneZh:'从一个细胞到一个完整的多细胞生物',sceneEn:'From one cell to a multicellular organism',options:[['细胞 → 器官 → 组织 → 系统 → 生物体','Cell → organ → tissue → system → organism'],['细胞 → 组织 → 器官 → 系统 → 生物体','Cell → tissue → organ → system → organism'],['组织 → 细胞 → 系统 → 器官 → 生物体','Tissue → cell → system → organ → organism']],answer:1,explainZh:'相似细胞组成组织，不同组织构成器官，器官协作形成系统。这里讨论的是具有这些结构的多细胞生物。',explainEn:'Cells form tissues; different tissues form organs; organs work together in systems. This sequence concerns multicellular organisms with these structures.'},
{id:'c2',page:'4',zh:'心脏含有肌肉、结缔等多种组织。它属于哪个层级？',en:'The heart contains muscle, connective, and other tissues. What level is it?',sceneZh:'多种组织，一起工作',sceneEn:'Different tissues working together',options:[['组织','Tissue'],['器官系统','Organ system'],['器官','Organ']],answer:2,explainZh:'器官由不同组织构成，共同完成特定功能。心脏属于器官，循环系统属于器官系统。',explainEn:'An organ combines different tissues to perform a function. The heart is an organ; the circulatory system is an organ system.'},
{id:'c3',page:'2–5',zh:'以下哪个例子属于细胞层级？',en:'Which example belongs to the cell level?',sceneZh:'一片叶、一个表皮细胞、一套根系',sceneEn:'A leaf, an epidermal cell, a root system',options:[['一片叶','A leaf'],['一个表皮细胞','An epidermal cell'],['一套根系','A root system']],answer:1,explainZh:'表皮细胞是一个细胞；叶由多种组织构成，是器官；根系属于器官系统。',explainEn:'An epidermal cell is one cell. A leaf contains multiple tissues and is an organ. A root system is an organ system.'},
{id:'c4',page:'5',zh:'胃和肠等器官协作，完成消化。这个协作整体属于什么？',en:'The stomach, intestines, and other organs cooperate in digestion. What is their coordinated group?',sceneZh:'多个器官，共同完成消化',sceneEn:'Several organs cooperate in digestion',options:[['器官系统','Organ system'],['组织','Tissue'],['种群','Population']],answer:0,explainZh:'不同器官共同完成一组相关功能，构成器官系统。这里是消化系统。',explainEn:'Different organs working together on related functions form an organ system: here, the digestive system.'},
{id:'c5',page:'6–7',zh:'一只青蛙，以及池塘内同一种青蛙的所有个体，分别是什么？',en:'One frog, and all the frogs of the same species in a pond, represent which levels?',sceneZh:'一只青蛙 → 同种青蛙的一群个体',sceneEn:'One frog → a group of the same species',options:[['生物体；群落','Organism; community'],['器官；生物体','Organ; organism'],['生物体；种群','Organism; population']],answer:2,explainZh:'生物体是一个生命个体。种群要求同一区域、同一物种。',explainEn:'An organism is one individual. A population requires the same area and the same species.'},
{id:'c6',page:'8',zh:'公园内所有植物、动物、真菌和微生物的种群共同构成什么？',en:'What do all plant, animal, fungal, and microbial populations in a park form?',sceneZh:'同一地区的不同生物种群',sceneEn:'Different living populations in one area',options:[['群落','Community'],['一个种群','One population'],['一个生物体','One organism']],answer:0,explainZh:'群落包括同一区域内不同物种的生物种群。因为存在多个物种，它们不是一个种群。',explainEn:'A community includes populations of different species in an area. Multiple species do not form a single population.'},
{id:'c7',page:'9',zh:'从群落到生态系统，还需要考虑什么？',en:'What must be considered in addition to a community to describe an ecosystem?',sceneZh:'公园里的生物，与它们生活的环境',sceneEn:'Life in a park and its surroundings',options:[['只增加更多动物','Only more animals'],['水、空气、土壤等非生物环境','Nonliving surroundings: water, air, and soil'],['只考虑同一个物种','Only one species']],answer:1,explainZh:'生态系统包括生物群落及非生物环境。它们之间的相互作用也是理解生态系统的关键。',explainEn:'An ecosystem includes the community and its nonliving environment. Their interactions are also central to understanding an ecosystem.'},
{id:'c8',page:'3–4',zh:'为什么一片叶是器官，而不是一种组织？',en:'Why is a leaf an organ rather than a tissue?',sceneZh:'叶的内部，也有分工',sceneEn:'A leaf has specialized internal structures',options:[['因为叶一定比所有细胞都大','Because leaves are always larger than every cell'],['因为绿色结构都叫器官','Because every green structure is an organ'],['因为不同组织在叶中协作','Because different tissues work together in a leaf']],answer:2,explainZh:'叶中的表皮组织、基本组织和维管组织分工协作。判断层级要看组成关系和功能，不能只看大小或颜色。',explainEn:'Dermal, ground, and vascular tissues cooperate within a leaf. Identify levels by their organization and functions, not just size or color.'}
];
window.PITFALLS=[
['这不是一条生长时间线','Not a growth timeline','细胞、组织、器官是不同的结构层次。单细胞生物的一个细胞就是整个生物体，并不需要长成组织和器官。','Cells, tissues, and organs are levels of structure. In a single-celled organism, one cell is the entire organism; it does not need to grow into tissues or organs.'],
['一个细胞，不等于一种组织','One cell is not a tissue','血细胞是细胞，血液属于结缔组织。木质部、韧皮部和形成层本身是组织名称；第2页将这些词列在细胞例子中，学习时需加以区分。','A blood cell is a cell; blood is connective tissue. Xylem, phloem, and cambium name tissues. Page 2 lists these terms with cells, so distinguish a tissue from its individual cells.'],
['“相似细胞”是入门简化','“Similar cells” is a simplification','第3页用相似细胞来定义组织，便于入门理解。但同一组织的细胞不一定完全相同；例如木质部、韧皮部包含多种细胞。','Page 3 defines tissues using similar cells as an introductory model. Cells in a tissue need not be identical; xylem and phloem include several cell types.'],
['根、根系、整株植物，观察范围不同','Root, root system, whole plant','一条根是器官；整套根系是器官系统；具有根和茎叶的完整植物是生物体。茎叶系统包含茎、叶和生殖结构；部分茎可在地下。','A root is an organ; the root system is an organ system; a whole plant with roots and shoots is an organism. The shoot system includes stems, leaves, and reproductive structures; some stems occur underground.'],
['种群看物种，群落看生物，生态系统还看环境','Species, living groups, then environment','种群必须是同一地区的同一物种。群落包含不同种群。水、岩石、空气等非生物因素进入讨论时，就需要考虑生态系统。','A population is one species in one area. A community contains different populations. When considering nonliving factors such as water, rocks, and air, consider the ecosystem.'],
['生命特征不是每个个体的逐项清单','Life processes are not an individual checklist','第6页总结典型生命活动。尚未繁殖或不能繁殖的个体仍然是生物；也不能把“利用气体”理解为所有生物都需要氧气。','Page 6 summarizes typical life processes. An individual that has not reproduced, or cannot reproduce, is still alive. “Uses gases” does not mean every organism needs oxygen.'],
['Monerans 是旧分类用语','Monerans is historical vocabulary','第6页同时出现 bacteria 和 monerans。Monera（原核生物界）是旧分类用语；现代入门分类通常区分细菌与古菌，不能把这两个原文例子当作现代分类中互不重叠的类群。','Page 6 lists both bacteria and monerans. Monera is an older grouping; modern introductory classification distinguishes Bacteria and Archaea. Do not treat the two source examples as separate, non-overlapping modern groups.']
];
window.PHOTO_HINTS={14:['观察竹秆（茎）本身。','Focus on a bamboo stem.'],27:['观察图中的肺这一结构。','Focus on the lungs.'],34:['观察图中主要的肝脏结构。','Focus on the liver.'],35:['观察突出显示的主根。','Focus on the prominent main root.'],39:['分别判断图中的小肠和大肠。','Classify the small and large intestines as individual structures.'],42:['判断带有根和茎叶的每一株植物。','Classify each plant with its root and leafy shoot.'],46:['观察枝条上的芽。','Focus on a bud on the twig.']};
