window.CELL_DATA={topics:[
{id:1,zh:'细胞学说与生命层次',en:'Cell theory & organization',short:'细胞学说',pages:'2–3',summaryZh:'抓住三句话：生物由细胞组成；细胞是生命的基本单位；细胞来自已有细胞。',summaryEn:'Living things are made of cells. Cells are the basic units of life. New cells arise from existing cells.',facts:[
{key:'theory',zh:'细胞学说',en:'Cell theory',structureZh:'无论生物多大、多复杂，细胞都是理解其生命活动的起点。',structureEn:'Cells are the starting point for understanding organisms, whatever their size or complexity.',jobZh:'已有细胞通过分裂形成新细胞，而不是凭空产生。',jobEn:'New cells form by division of pre-existing cells, rather than appearing spontaneously.'},
{key:'organization',zh:'单细胞与多细胞',en:'Unicellular & multicellular',structureZh:'单细胞生物由一个细胞构成；多细胞生物由许多细胞构成。',structureEn:'Unicellular organisms consist of one cell; multicellular organisms consist of many cells.',jobZh:'多细胞生物中的细胞可组织成组织、器官和器官系统。',jobEn:'Cells in multicellular organisms may be organized into tissues, organs, and organ systems.'}],flow:[['细胞','Cells'],['组织','Tissues'],['器官','Organs'],['器官系统','Organ systems']]},
{id:2,zh:'两类细胞，共同基础',en:'Two cell types, shared essentials',short:'原核与真核',pages:'4–7',summaryZh:'判断原核与真核，先看有没有由膜包围的细胞核。两类细胞都需要边界、内部环境、蛋白质合成工具和遗传信息。',summaryEn:'Start with the nucleus: is it enclosed by a membrane? Both cell types need a boundary, an internal medium, protein-making machinery, and genetic information.',facts:[
{key:'prokaryote',zh:'原核细胞',en:'Prokaryotic cell',structureZh:'没有膜包围的细胞核，也没有膜性细胞器。课堂例子是细菌。',structureEn:'No membrane-bound nucleus or membrane-bound organelles. Bacteria are the classroom example.',jobZh:'原核生物为单细胞生物，通常通过二分裂繁殖。',jobEn:'Prokaryotic organisms are unicellular and usually reproduce by binary fission.'},
{key:'eukaryote',zh:'真核细胞',en:'Eukaryotic cell',structureZh:'有细胞核和膜性细胞器。动物、植物、真菌和原生生物属于真核生物。',structureEn:'Has a nucleus and membrane-bound organelles. Animals, plants, fungi, and protists are eukaryotes.',jobZh:'真核生物可以是单细胞或多细胞；身体细胞常通过有丝分裂产生。',jobEn:'Eukaryotes can be unicellular or multicellular; body cells commonly form through mitosis.'},
{key:'shared',zh:'共同的四种结构',en:'Four shared components',structureZh:'细胞膜、细胞质、核糖体、遗传物质 DNA。',structureEn:'Plasma membrane, cytoplasm, ribosomes, and DNA as hereditary material.',jobZh:'记忆：边界、环境、合成、信息。核糖体没有膜，因此原核细胞也能拥有。',jobEn:'Remember: boundary, medium, synthesis, information. Ribosomes are not membrane-bound, so prokaryotes have them too.'},
{key:'organelles',zh:'细胞器',en:'Organelles',structureZh:'细胞内部承担特定任务的结构，可理解为协作的“小器官”。',structureEn:'Specialized structures within cells can be thought of as cooperating “mini organs.”',jobZh:'共同支持蛋白质制造、运输、能量转化、储存和分解。',jobEn:'They support protein production, transport, energy conversion, storage, and breakdown.'}],noteZh:'讲义第 6 页写“DNA 或 RNA”。更准确地说，细胞的遗传物质是 DNA，RNA 也参与重要生命过程。原核生物还包括古菌；肽聚糖细胞壁是大多数细菌的特征，不能推广到所有原核生物。有丝分裂也不是所有真核细胞唯一的分裂方式。',noteEn:'Cellular hereditary material is DNA; RNA also plays essential roles. Prokaryotes include archaea, so peptidoglycan walls are not universal. Eukaryotes can also undergo meiosis.',sources:[['OpenStax · Prokaryotic cells','https://openstax.org/books/biology-2e/pages/4-2-prokaryotic-cells'],['Bacteria & Archaea','https://openstax.org/books/biology-2e/pages/22-2-structure-of-prokaryotes-bacteria-and-archaea']]},
{id:3,zh:'边界、环境与支撑',en:'Boundary, medium & support',short:'细胞膜与支撑',pages:'10–13',summaryZh:'细胞膜控制进出，细胞质提供内部环境，细胞骨架维持形态并帮助内部运输。',summaryEn:'The membrane regulates exchange, cytoplasm provides the internal medium, and the cytoskeleton supports shape and movement.',facts:[
{key:'membrane',zh:'细胞膜（质膜）',en:'Cell / plasma membrane',structureZh:'包围细胞的磷脂双分子层，嵌有蛋白质。',structureEn:'A phospholipid bilayer with embedded proteins surrounds the cell.',jobZh:'调控物质进入和离开细胞，具有选择透过性。',jobEn:'Regulates what enters and leaves the cell; it is selectively permeable.'},
{key:'bilayer',zh:'流动镶嵌模型',en:'Fluid-mosaic model',structureZh:'“双层”指两层磷脂；“镶嵌”指不同成分相互组合。',structureEn:'“Bilayer” means two phospholipid layers; “mosaic” refers to the mixture of components.',jobZh:'“流动”表示膜中的许多成分可以移动，细胞膜不是固定不动的硬壳。',jobEn:'“Fluid” means many components can move within the membrane; it is not a rigid shell.'},
{key:'cytoplasm',zh:'细胞质',en:'Cytoplasm',structureZh:'讲义将其描述为主要由水构成的胶状物质。',structureEn:'The notes describe a jelly-like interior composed mainly of water.',jobZh:'为细胞内各种结构及活动提供环境。',jobEn:'Provides an internal environment for cell structures and activities.'},
{key:'cytoskeleton',zh:'细胞骨架',en:'Cytoskeleton',structureZh:'蛋白质构成的丝状纤维网络；简化细胞图中常不画出。',structureEn:'A network of threadlike protein fibers, often omitted from simplified cell diagrams.',jobZh:'维持形态、提供支撑，并帮助细胞器移动。',jobEn:'Maintains shape, provides support, and helps move organelles.'}],image:'membrane',noteZh:'图中词汇：hydrophilic heads = 亲水头部；hydrophobic tails = 疏水尾部；protein channel = 蛋白质通道。细胞质不是把一切固定不动的“胶水”。',noteEn:'The cytoplasm is a dynamic environment, not glue that keeps everything still. The cytoskeleton helps position and transport components.'},
{id:4,zh:'遗传信息与核糖体的起点',en:'DNA and the origin of ribosomes',short:'细胞核与核仁',pages:'14–15',summaryZh:'细胞核保护 DNA；核仁位于核内，与核糖体的形成有关。',summaryEn:'The nucleus protects DNA. The nucleolus sits inside it and helps form ribosomes.',facts:[
{key:'nucleus',zh:'细胞核',en:'Nucleus',structureZh:'含有 DNA；外有核膜（核被膜），膜上有核孔。',structureEn:'Contains DNA and is enclosed by a nuclear envelope with nuclear pores.',jobZh:'保护遗传信息。DNA 中的信息参与调控细胞活动，核孔调节核内外物质交换。',jobEn:'Protects genetic information that directs cell activities; pores regulate exchange with the nucleus.'},
{key:'nucleolus',zh:'核仁',en:'Nucleolus',structureZh:'位于细胞核内部，不要与整个细胞核混淆。',structureEn:'Located inside the nucleus; it is not the whole nucleus.',jobZh:'制造 rRNA（核糖体 RNA），并参与核糖体亚基的组装。',jobEn:'Produces rRNA (ribosomal RNA) and helps assemble ribosomal subunits.'}],noteZh:'理解补充：核仁不仅制造 rRNA，还参与核糖体亚基组装。',noteEn:'The nucleolus also helps assemble ribosomal subunits.',sources:[['OpenStax · Eukaryotic cells','https://openstax.org/books/biology-2e/pages/4-3-eukaryotic-cells']]},
{id:5,zh:'蛋白质在哪里制造？',en:'Where are proteins made?',short:'核糖体与粗面内质网',pages:'16–17',summaryZh:'真正合成蛋白质的是核糖体。粗面内质网因附着核糖体而显得“粗糙”。',summaryEn:'Ribosomes synthesize proteins. Rough ER looks “rough” because ribosomes attach to its surface.',facts:[
{key:'ribosome',zh:'核糖体',en:'Ribosome',structureZh:'由蛋白质和 rRNA 构成；可以游离于细胞质中，也可附着在粗面内质网上。',structureEn:'Made of proteins and rRNA; found free in the cytoplasm or attached to rough ER.',jobZh:'合成蛋白质。原核细胞和真核细胞都拥有核糖体。',jobEn:'Synthesizes proteins. Both prokaryotic and eukaryotic cells have ribosomes.'},
{key:'rough-er',zh:'粗面内质网',en:'Rough endoplasmic reticulum · RER',structureZh:'靠近细胞核的膜性结构，表面附有核糖体。',structureEn:'A membrane network near the nucleus with ribosomes on its surface.',jobZh:'表面核糖体合成蛋白质，内质网参与其加工和运输。',jobEn:'Attached ribosomes synthesize proteins; the ER helps process and transport them.'}],noteZh:'讲义将粗面内质网的工作简写成“制造蛋白质”。精确区分：核糖体执行合成，粗面内质网为相关加工和运输提供场所。',noteEn:'Distinguish synthesis by ribosomes from processing and transport associated with rough ER.',sources:[['OpenStax · Endomembrane system','https://openstax.org/books/biology-2e/pages/4-4-the-endomembrane-system-and-proteins']]},
{id:6,zh:'制造脂质，分拣与运输',en:'Lipid synthesis, sorting & shipping',short:'光面内质网与高尔基体',pages:'18–19',summaryZh:'光面内质网主要与脂质合成有关；高尔基体接收、加工和分拣货物，囊泡负责运输。',summaryEn:'Smooth ER makes lipids. The Golgi receives, processes, and sorts cargo; vesicles transport it.',facts:[
{key:'smooth-er',zh:'光面内质网',en:'Smooth endoplasmic reticulum · SER',structureZh:'与粗面内质网相连，表面没有附着的核糖体。',structureEn:'Connected to rough ER, without attached ribosomes on its surface.',jobZh:'合成脂质，包括用于构成细胞膜的脂质。',jobEn:'Synthesizes lipids, including those used in membranes.'},
{key:'golgi',zh:'高尔基体',en:'Golgi apparatus',structureZh:'由层叠的膜性囊构成，接收来自内质网的运输囊泡。',structureEn:'Stacks of membrane sacs receive transport vesicles from the ER.',jobZh:'对蛋白质等物质进行加工、分类，并送往需要的地方。',jobEn:'Processes and sorts proteins and other materials, then sends them to their destinations.'},
{key:'vesicle',zh:'囊泡',en:'Vesicle',structureZh:'膜包围的小囊，可类比运送货物的小车。',structureEn:'A small membrane-bound sac, like a cart carrying cargo.',jobZh:'在内质网、高尔基体和其他目的地之间运输物质。',jobEn:'Transports materials between the ER, Golgi, and other destinations.'}],flow:[['粗面内质网','Rough ER'],['运输囊泡','Vesicle'],['高尔基体','Golgi'],['送往目的地','Destination']]},
{id:7,zh:'回收与储存',en:'Recycling & storage',short:'溶酶体与液泡',pages:'20–21, 27',summaryZh:'“分解”想到溶酶体，“储存”想到液泡。典型成熟植物细胞中，中央液泡特别大。',summaryEn:'Think lysosomes for digestion and vacuoles for storage. A typical mature plant cell has a large central vacuole.',facts:[
{key:'lysosome',zh:'溶酶体',en:'Lysosome',structureZh:'内部含有用于分解物质的酶，常见于教材中的动物细胞。',structureEn:'Contains digestive enzymes; commonly shown in textbook animal cells.',jobZh:'分解食物颗粒、细菌和老旧细胞结构，回收可用物质。',jobEn:'Digests food particles, bacteria, and worn cell components, recycling useful materials.'},
{key:'vacuole',zh:'液泡',en:'Vacuole',structureZh:'膜包围的储存结构。讲义中的动物细胞液泡较小，可有多个。',structureEn:'A membrane-bound storage compartment. The notes show smaller, multiple vacuoles in animal cells.',jobZh:'储存水、营养物质和废物。',jobEn:'Stores water, nutrients, and wastes.'},
{key:'central-vacuole',zh:'中央液泡',en:'Central vacuole',structureZh:'典型成熟植物细胞中的大型中央结构，常占据很大空间。',structureEn:'A large central compartment that occupies much of a typical mature plant cell.',jobZh:'储存物质；内部水分还帮助维持膨压，支撑细胞。',jobEn:'Stores materials; water inside also helps maintain turgor pressure and support the cell.'}],noteZh:'讲义提到 apoptosis（细胞凋亡），即受调控的细胞死亡。溶酶体可参与某些细胞死亡过程，但不能把凋亡简单理解为“溶酶体消化整个细胞”。植物的液泡也可承担消化功能。',noteEn:'Apoptosis is regulated cell death, not simply a lysosome digesting a whole cell. Plant vacuoles can also have digestive roles.',sources:[['NCBI Bookshelf · Programmed cell death','https://www.ncbi.nlm.nih.gov/books/NBK26873/'],['OpenStax · Eukaryotic cells','https://openstax.org/books/biology-2e/pages/4-3-eukaryotic-cells']]},
{id:8,zh:'分裂与运动',en:'Cell division & movement',short:'中心体、纤毛与鞭毛',pages:'22–23',summaryZh:'中心体参与组织分裂用的微管；纤毛通常短而多；鞭毛通常长而少。',summaryEn:'Centrosomes organize microtubules used in division. Cilia are usually short and numerous; flagella are longer and fewer.',facts:[
{key:'centrosome',zh:'中心体与中心粒',en:'Centrosome & centrioles',structureZh:'典型动物细胞的中心体含中心粒；中心粒由微管构成。',structureEn:'A typical animal-cell centrosome contains centrioles made of microtubules.',jobZh:'中心体组织微管，参与形成分裂纺锤体。纺锤体帮助分离染色体。',jobEn:'The centrosome organizes microtubules for the spindle that helps separate chromosomes.'},
{key:'cilia',zh:'纤毛',en:'Cilia',structureZh:'通常较短、数量较多，像许多小桨。',structureEn:'Usually short and numerous, like many tiny oars.',jobZh:'可推动细胞表面的液体，也可推动整个细胞。',jobEn:'Can move fluid across a cell surface or propel an entire cell.'},
{key:'flagella',zh:'鞭毛',en:'Flagella',structureZh:'通常较长、数量较少。讲义中的“1–3 根”是简化示例。',structureEn:'Usually longer and fewer. The notes’ “1–3” is a simplified example.',jobZh:'帮助细胞移动。细菌鞭毛与真核细胞鞭毛的结构不同。',jobEn:'Helps propel cells. Bacterial flagella differ structurally from eukaryotic flagella.'}],noteZh:'中心体不是到分裂时才突然出现。纤毛和鞭毛也并非只见于动物或细菌，例如一些原生生物也有这些运动结构。',noteEn:'Centrosomes exist before division. Cilia and flagella also occur in some protists; they are not limited to animals and bacteria.',sources:[['OpenStax · Cytoskeleton','https://openstax.org/books/biology-2e/pages/4-5-the-cytoskeleton']]},
{id:9,zh:'细胞怎样转化能量？',en:'How cells transform energy',short:'线粒体与叶绿体',pages:'24–25',summaryZh:'线粒体把食物中的能量转化为 ATP；叶绿体把光能转化为糖中的化学能。植物也需要线粒体。',summaryEn:'Mitochondria convert food-derived energy into ATP. Chloroplasts convert light energy into chemical energy in sugars. Plants need mitochondria too.',facts:[
{key:'mitochondria',zh:'线粒体',en:'Mitochondrion · plural: mitochondria',structureZh:'重点识别内膜和基质（matrix）；内膜折叠形成嵴。',structureEn:'Recognize the inner membrane and matrix; inner-membrane folds form cristae.',jobZh:'是细胞呼吸的重要场所，利用食物中的能量制造 ATP。',jobEn:'A major site of cellular respiration, using energy from food to produce ATP.'},
{key:'chloroplast',zh:'叶绿体',en:'Chloroplast',structureZh:'重点识别基粒（grana，膜囊的堆叠）与基质（stroma，周围液体）。',structureEn:'Recognize grana (stacks of membrane sacs) and stroma (the surrounding fluid).',jobZh:'进行光合作用，利用太阳光能帮助制造糖。',jobEn:'Performs photosynthesis, capturing sunlight to help make sugars.'}],noteZh:'讲义的“两部分”是记忆重点，不是完整结构清单：两种细胞器都有外膜和内膜。并非所有植物细胞都有叶绿体，藻类也可有叶绿体。',noteEn:'The notes list key parts, not every component. Both organelles have outer and inner membranes. Not all plant cells have chloroplasts; algae may have them too.',sources:[['OpenStax · Eukaryotic cells','https://openstax.org/books/biology-2e/pages/4-3-eukaryotic-cells']]},
{id:10,zh:'从结构辨认细胞',en:'Recognize cells by their structures',short:'细胞壁与动植物对照',pages:'8–9, 26, 28–31',summaryZh:'比较典型动物与植物细胞：二者都是有细胞核的真核细胞；细胞壁、叶绿体和大型中央液泡是植物细胞图的重要线索。',summaryEn:'Typical animal and plant cells are both eukaryotic. A wall, chloroplasts, and a large central vacuole are key clues in the plant-cell diagram.',facts:[
{key:'wall',zh:'细胞壁',en:'Cell wall',structureZh:'位于细胞膜外。植物：纤维素（cellulose）；真菌：几丁质（chitin）；多数细菌：肽聚糖（peptidoglycan）。',structureEn:'Outside the membrane. Plants: cellulose; fungi: chitin; most bacteria: peptidoglycan.',jobZh:'保护细胞并帮助维持形态。动物细胞没有细胞壁。',jobEn:'Protects cells and helps maintain shape. Animal cells lack a cell wall.'},
{key:'comparison',zh:'动物与植物细胞',en:'Animal & plant cells',structureZh:'共同点：细胞膜、细胞质、细胞核、核糖体、内质网、高尔基体和线粒体。',structureEn:'Shared structures: membrane, cytoplasm, nucleus, ribosomes, ER, Golgi, and mitochondria.',jobZh:'图中植物细胞还有细胞壁、叶绿体和大型中央液泡。不要把“有细胞壁”等同于“是植物”，还要结合其他结构判断。',jobEn:'The plant diagram also shows a wall, chloroplasts, and a large central vacuole. A wall alone does not prove a cell is a plant cell.'}],noteZh:'讲义第 26 页末尾漏掉了真菌；请记住真菌也有细胞壁。这里比较的是典型教材模型，不能把图中的特征推广为所有细胞的绝对规则。',noteEn:'Fungi also have cell walls. These are typical textbook models, not universal rules for every cell.',sources:[['OpenStax · Eukaryotic cells','https://openstax.org/books/biology-2e/pages/4-3-eukaryotic-cells']]}
],questions:[
  {"id":1,"zh":"哪项说法符合细胞学说？","en":"Which statement agrees with cell theory?","options":[{"zh":"每个生物都由许多细胞组成。","en":"Every living organism contains many cells."},{"zh":"新细胞不需要已有细胞就能形成。","en":"New cells form without pre-existing cells."},{"zh":"细胞是生命的基本单位，并由已有细胞产生。","en":"Cells are life's basic units and arise from existing cells."},{"zh":"器官是最小的生命单位。","en":"Organs are the smallest living units."}],"answer":2,"explainZh":"生物由细胞组成。单细胞生物只有一个细胞；多细胞生物有许多细胞，可形成组织、器官和器官系统。","explainEn":"Living things consist of cells. Unicellular organisms have one cell; multicellular organisms have many, which may form tissues, organs, and organ systems."},
  {"id":2,"zh":"哪项正确比较了典型的原核细胞和真核细胞？","en":"Which comparison correctly describes typical prokaryotic and eukaryotic cells?","options":[{"zh":"原核细胞没有膜包围的细胞核；真核细胞有。","en":"Prokaryotes lack a membrane-bound nucleus; eukaryotes have one."},{"zh":"只有真核细胞有核糖体。","en":"Only eukaryotes have ribosomes."},{"zh":"只有原核细胞有细胞膜。","en":"Only prokaryotes have a cell membrane."},{"zh":"所有真核生物都是多细胞生物。","en":"All eukaryotic organisms are multicellular."}],"answer":0,"explainZh":"两类细胞都具有细胞膜、细胞质、核糖体和 DNA。真核细胞有膜性细胞器，真核生物可以是单细胞或多细胞。","explainEn":"Both share a membrane, cytoplasm, ribosomes, and DNA. Eukaryotes have membrane-bound organelles and may be unicellular or multicellular."},
  {"id":3,"zh":"哪组正确对应了细胞膜、细胞质和细胞骨架的特点？","en":"Which set correctly matches the membrane, cytoplasm, and cytoskeleton?","options":[{"zh":"细胞膜：储存 DNA；细胞质：坚硬外壳；细胞骨架：制造糖","en":"Membrane: stores DNA; cytoplasm: rigid shell; cytoskeleton: makes sugars"},{"zh":"细胞膜：调控进出；细胞质：富含水的内部环境；细胞骨架：支撑细胞的蛋白质纤维","en":"Membrane: regulates exchange; cytoplasm: watery interior; cytoskeleton: supporting protein fibers"},{"zh":"细胞膜：制造 ATP；细胞质：细胞壁；细胞骨架：消化囊","en":"Membrane: makes ATP; cytoplasm: cell wall; cytoskeleton: digestive sac"},{"zh":"细胞膜：完全不透；细胞质：纯 DNA；细胞骨架：纯脂质","en":"Membrane: completely impermeable; cytoplasm: pure DNA; cytoskeleton: pure lipid"}],"answer":1,"explainZh":"细胞膜是含蛋白质的磷脂双分子层；细胞质提供内部环境；细胞骨架维持形态并帮助移动细胞器。","explainEn":"The membrane is a phospholipid bilayer with proteins. Cytoplasm provides an internal medium; the cytoskeleton maintains shape and helps move organelles."},
  {"id":4,"zh":"细胞核和核仁的主要功能分别是什么？","en":"What are the main roles of the nucleus and nucleolus?","options":[{"zh":"细胞核制造脂质，核仁消化食物。","en":"The nucleus makes lipids; the nucleolus digests food."},{"zh":"细胞核进行光合作用，核仁储存水。","en":"The nucleus performs photosynthesis; the nucleolus stores water."},{"zh":"细胞核包装蛋白质，核仁推动细胞。","en":"The nucleus packages proteins; the nucleolus propels the cell."},{"zh":"细胞核保护 DNA，核仁制造 rRNA 并参与组装核糖体亚基。","en":"The nucleus protects DNA; the nucleolus makes rRNA and helps assemble ribosomal subunits."}],"answer":3,"explainZh":"细胞核内的 DNA 提供遗传信息，核孔调控核内外的物质交换。核仁位于细胞核内部，与核糖体形成有关。","explainEn":"Nuclear DNA provides genetic information, and nuclear pores regulate exchange. The nucleolus lies inside the nucleus and helps form ribosomes."},
  {"id":5,"zh":"粗面内质网为什么看起来“粗糙”？这些附着结构有什么作用？","en":"Why does rough ER look rough, and what do its attached structures do?","options":[{"zh":"表面附着核糖体，它们合成蛋白质。","en":"Ribosomes are attached to its surface; they synthesize proteins."},{"zh":"表面附着叶绿体，它们捕获光能。","en":"Chloroplasts are attached; they capture light."},{"zh":"表面附着液泡，它们储存水。","en":"Vacuoles are attached; they store water."},{"zh":"表面附着纤毛，它们推动液体。","en":"Cilia are attached; they move fluid."}],"answer":0,"explainZh":"核糖体由 rRNA 和蛋白质构成，可以游离于细胞质中，也可以附着在粗面内质网上。粗面内质网参与蛋白质的加工和运输。","explainEn":"Ribosomes contain rRNA and proteins and may be free in the cytoplasm or attached to rough ER. Rough ER helps process and transport proteins."},
  {"id":6,"zh":"哪组正确描述了光面内质网、高尔基体和囊泡的协作？","en":"Which set correctly describes smooth ER, the Golgi apparatus, and vesicles?","options":[{"zh":"光面内质网储存 DNA；高尔基体制造 rRNA；囊泡进行光合作用。","en":"Smooth ER stores DNA; Golgi makes rRNA; vesicles perform photosynthesis."},{"zh":"光面内质网合成脂质；高尔基体加工分类；囊泡运输物质。","en":"Smooth ER makes lipids; Golgi processes and sorts; vesicles transport materials."},{"zh":"光面内质网有大量核糖体；高尔基体只储存水；囊泡分离染色体。","en":"Smooth ER is covered in ribosomes; Golgi only stores water; vesicles separate chromosomes."},{"zh":"三者的唯一功能都是制造 ATP。","en":"All three only make ATP."}],"answer":1,"explainZh":"光面内质网没有附着的核糖体，参与脂质合成。高尔基体接收来自内质网的囊泡，对其中的蛋白质等物质加工、分类并运送。","explainEn":"Smooth ER lacks attached ribosomes and synthesizes lipids. The Golgi receives ER vesicles, then processes, sorts, and ships their contents, including proteins."},
  {"id":7,"zh":"哪组正确比较了溶酶体和液泡？","en":"Which pair correctly compares lysosomes and vacuoles?","options":[{"zh":"溶酶体进行光合作用；液泡合成蛋白质。","en":"Lysosomes perform photosynthesis; vacuoles synthesize proteins."},{"zh":"溶酶体储存染色体；液泡推动细胞运动。","en":"Lysosomes store chromosomes; vacuoles move cells."},{"zh":"溶酶体用酶分解物质；液泡储存水、营养物质和废物。","en":"Lysosomes digest materials using enzymes; vacuoles store water, nutrients, and wastes."},{"zh":"溶酶体合成脂质；液泡制造 rRNA。","en":"Lysosomes synthesize lipids; vacuoles make rRNA."}],"answer":2,"explainZh":"溶酶体参与消化和回收老旧细胞结构。典型成熟植物细胞的大型中央液泡既能储存物质，也有助于维持膨压。","explainEn":"Lysosomes digest and recycle worn cell components. The large central vacuole of a typical mature plant cell stores materials and helps maintain turgor."},
  {"id":8,"zh":"哪组正确描述了中心体、纤毛和鞭毛的常见功能？","en":"Which set gives the usual roles of centrosomes, cilia, and flagella?","options":[{"zh":"中心体：光合作用；纤毛：储存；鞭毛：消化","en":"Centrosome: photosynthesis; cilia: storage; flagellum: digestion"},{"zh":"中心体：合成 DNA；纤毛：制造脂质；鞭毛：制造蛋白质","en":"Centrosome: DNA synthesis; cilia: lipids; flagellum: proteins"},{"zh":"中心体：储存；纤毛：包装蛋白质；鞭毛：制造 ATP","en":"Centrosome: storage; cilia: protein packaging; flagellum: ATP synthesis"},{"zh":"中心体：组织分裂所需的微管；纤毛：推动表面液体；鞭毛：推动细胞","en":"Centrosome: organizes division microtubules; cilia: move surface fluid; flagellum: propels a cell"}],"answer":3,"explainZh":"中心体中的中心粒由微管构成。中心体组织参与动物细胞分裂的微管；纤毛通常短而多，鞭毛通常长而少。","explainEn":"Centrioles in the centrosome are made of microtubules. Centrosomes organize division microtubules; cilia are usually short and numerous, while flagella are longer and fewer."},
  {"id":9,"zh":"哪组正确比较了线粒体和叶绿体？","en":"Which pairing correctly compares mitochondria and chloroplasts?","options":[{"zh":"线粒体：呼吸作用与 ATP；叶绿体：光合作用与糖","en":"Mitochondria: respiration and ATP; chloroplasts: photosynthesis and sugars"},{"zh":"线粒体：光合作用；叶绿体：消化","en":"Mitochondria: photosynthesis; chloroplasts: digestion"},{"zh":"线粒体：运输蛋白质；叶绿体：移动染色体","en":"Mitochondria: protein shipping; chloroplasts: chromosome movement"},{"zh":"两者都只储存水和废物。","en":"Both only store water and wastes."}],"answer":0,"explainZh":"线粒体将食物中的能量转化为 ATP，内部有线粒体基质。叶绿体捕获光能以帮助合成糖，内部有基粒和叶绿体基质。植物细胞也有线粒体。","explainEn":"Mitochondria convert food-derived energy into ATP and contain a matrix. Chloroplasts capture light to help make sugars and contain grana and stroma. Plant cells also have mitochondria."},
  {"id":10,"zh":"细胞图中有纤维素细胞壁、叶绿体和大型中央液泡，最符合哪种细胞？","en":"A diagram shows a cellulose wall, chloroplasts, and a large central vacuole. Which cell best fits?","options":[{"zh":"典型的动物细胞","en":"A typical animal cell"},{"zh":"细菌细胞","en":"A bacterial cell"},{"zh":"能进行光合作用的植物细胞","en":"A photosynthetic plant cell"},{"zh":"典型的真菌细胞","en":"A typical fungal cell"}],"answer":2,"explainZh":"这组结构符合教材中的植物细胞模型。动物细胞没有细胞壁；真菌细胞壁主要含几丁质；细菌没有叶绿体。细胞壁有助于保护细胞并维持形态。","explainEn":"This combination matches the plant-cell model. Animals lack cell walls; fungal walls mainly contain chitin; bacteria lack chloroplasts. Cell walls help protect cells and maintain shape."}
]
};
