const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const base=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(base,f),'utf8');
const json=f=>JSON.parse(read(f).replace(/^\uFEFF/,''));
const write=(f,value)=>fs.writeFileSync(path.join(base,f),value);
function data(files){const ctx={};ctx.window=ctx;vm.createContext(ctx);files.forEach(f=>vm.runInContext(read(f),ctx));return ctx;}
const l=data(['units/levels/data.js','units/levels/learning.js']),c=data(['units/cells/data.js']).CELL_DATA;
const biology=json('data/biology-objectives.json'),biologyPages=json('data/biology-source-pages.json');
const points=[...l.LEVELS.map(p=>({id:'levels-'+p.id,key:p.id,unit:'levels',title:p.en,pages:String(p.page),href:'units/levels/index.html#level-'+p.id,verified:true})),{id:'levels-hierarchy',key:'hierarchy',unit:'levels',title:'Structural hierarchy and relationships',pages:'1–9',href:'units/levels/index.html#hierarchy',verified:true},{id:'levels-life-processes',key:'life-processes',unit:'levels',title:'Life processes',pages:'6',href:'units/levels/index.html#life-processes',verified:true},...c.topics.flatMap(t=>t.facts.map(f=>({id:'cells-'+f.key,key:f.key,unit:'cells',title:f.en,pages:t.pages,href:'units/cells/index.html#fact-'+f.key,verified:false,topic:t.id})))];
for(const o of biology){const canonical=o.relatedCellKey?'cells-'+o.relatedCellKey:'biology-'+o.key;if(o.relatedCellKey&&!points.some(p=>p.id===canonical))throw Error('Unknown related concept '+canonical);points.push({id:'biology-'+o.key,key:o.key,unit:'biology',title:o.title,pages:o.pages.join(', '),href:'units/biology/index.html#point-'+o.key,verified:true,canonical});}
points.forEach(p=>p.canonical??=p.id);
const questions=[...json('data/levels-questions.json').map(q=>({...q,unit:'levels',points:['levels-'+q.pointKey]})),...json('data/cells-questions.json').map(q=>({...q,unit:'cells',points:['cells-'+q.pointKey]}))];
const conceptPoints={c1:['hierarchy'],c2:['organ'],c3:['cell'],c4:['system'],c5:['organism','population'],c6:['community'],c7:['ecosystem'],c8:['tissue','organ']};
l.CONCEPTS.forEach(q=>questions.push({id:'levels-original-'+q.id,unit:'levels',stem:q.en,options:q.options.map(o=>o[1]),answer:q.answer,explanation:q.explainEn,pages:q.page,points:conceptPoints[q.id].map(k=>'levels-'+k)}));
const discussions=[];
l.PHOTO_ITEMS.forEach(q=>{const level=l.LEVELS.find(p=>p.id===q.level);const row={id:'levels-photo-'+q.page,unit:'levels',stem:`Which level of organization does the highlighted subject represent? ${l.PHOTO_HINTS[q.page]?.[1]||'Classify the main subject in the image.'}`,image:'units/levels/images/'+q.image,imageAlt:'Classification exercise from source page '+q.page,options:l.LEVELS.slice(0,5).map(p=>p.en),answer:l.LEVELS.findIndex(p=>p.id===q.level),explanation:`${q.subjectEn}: ${level.en}. ${level.defEn} ${q.noteEn||''}`,pages:String(q.page),points:['levels-'+q.level]};([38,50].includes(q.page)?discussions:questions).push(row);});
const cellOldMap={1:['theory'],2:['prokaryote','eukaryote'],3:['membrane','cytoplasm','cytoskeleton'],4:['nucleus','nucleolus'],5:['ribosome','rough-er'],6:['smooth-er','golgi','vesicle'],7:['lysosome','vacuole'],8:['centrosome','cilia','flagella'],9:['mitochondria','chloroplast'],10:['comparison']};
c.questions.forEach(q=>{const ids=cellOldMap[q.id].map(k=>'cells-'+k);for(const id of ids)if(!points.some(p=>p.id===id))throw Error('Unknown mapped point '+id);questions.push({id:'cells-original-'+q.id,unit:'cells',stem:q.en,options:q.options.map(o=>o.en),answer:q.answer,explanation:q.explainEn,pages:c.topics.find(t=>t.id===q.id).pages,points:ids});});
for(const o of biology)for(const [i,q] of o.questions.entries())questions.push({...q,id:`biology-${o.key}-${q.suffix||i+1}`,unit:'biology',pages:o.pages.join(', '),points:['biology-'+o.key]});
const topics=['Levels of Organization','Cell Structure and Function','Cell Cycle: Mitosis and Meiosis','Photosynthesis and Cellular Respiration','Viruses','Evolution','Genetic Engineering','Asexual and Sexual Reproduction','Immunization and Vaccination'];
const units=[{id:'levels',title:'Levels of Organization Notes',topic:0,description:'Explore eight levels of life, from cells to ecosystems, with the original picture exercises.',href:'units/levels/index.html',image:'units/levels/images/page-12.jpg',imageAlt:'An example from the organization lesson',pages:52,verified:true},{id:'biology',title:'Cell Biology',topic:1,description:'Follow the history of cell theory, explore cell structures, and experiment with transport, osmosis and cell size.',href:'units/biology/index.html',image:'units/biology/pages/page-01.jpg',imageAlt:'Cell Biology lecture cover',pages:43,verified:true},{id:'cells',title:'Concept 1 · Cell Theory and Organelles',topic:1,description:'Explore animal and plant cells, connect structures with functions, and practise each learning objective.',href:'units/cells/index.html',image:'units/cells/assets/animal.png',imageAlt:'Animal cell diagram',pages:31,verified:false}];
for(const u of units){u.pointCount=points.filter(p=>p.unit===u.id).length;u.questionCount=questions.filter(q=>q.unit===u.id).length;}
const uniquePointCount=new Set(points.map(p=>p.canonical)).size;
const countingRule=`Each lesson keeps its complete learning objectives (${points.length} lesson-level entries). Repeated named cell/structure concepts explicitly linked between Cell Biology and Concept 1 count once in the course total: ${uniquePointCount} distinct concepts. Lesson-specific details and questions remain separate. Definitions, functions and examples are grouped into objectives rather than counted as individual factual statements.`;
const result={version:1,title:'LifeScience 11',topics,units,points,questions,discussions,uniquePointCount,countingRule};
write('course-data.js','window.COURSE_DATA='+JSON.stringify(result)+';\n');write('units/biology/biology-data.js','window.BIOLOGY_DATA='+JSON.stringify({objectives:biology,sourcePages:biologyPages})+';\n');
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const rows=points.map(p=>({unit:p.unit,sourcePages:p.pages,pointId:p.id,canonical:p.canonical,title:p.title,website:p.href,questions:questions.filter(q=>q.points.includes(p.id)).map(q=>q.id),sourceVerified:p.verified}));
const sourcePages=Array.from({length:52},(_,i)=>{const page=i+1;return{unit:'levels',page,points:page===1?['levels-hierarchy']:page<=9?['levels-'+l.LEVELS[page-2].id,...(page===6?['levels-life-processes']:[])]:['levels-'+l.PHOTO_ITEMS.find(p=>p.page===page).level],website:page===1?'units/levels/index.html#hierarchy':page<=9?points[page-2].href:'units/levels/index.html#photo-'+page,questions:page>=10?['levels-photo-'+page]:questions.filter(q=>q.unit==='levels'&&q.pages===String(page)).map(q=>q.id),status:[38,50].includes(page)?'Discussion; excluded from scoring':'Verified'};});
for(const page of biologyPages){const related=biology.filter(o=>o.pages.includes(page.page));const ids=related.map(o=>'biology-'+o.key);sourcePages.push({unit:'biology',page:page.page,points:ids,website:'units/biology/index.html#source-'+page.page,questions:questions.filter(q=>q.points.some(id=>ids.includes(id))).map(q=>q.id),status:page.page<=2?'Title/agenda preserved; no separate assessment required':'Verified against supplied PDF',clarifications:related.filter(o=>o.clarification).map(o=>({pointId:'biology-'+o.key,text:o.clarification}))});}
const sourceStatus={levels:'Verified against the supplied 52-page Levels PDF.',biology:'Verified against the supplied 43-page Cell Biology PDF. Distinct from the 31-page Concept 1 lecture. All page images and extracted text retained; teaching corrections documented.',cells:'Original 31-page Concept 1 PDF/PPT still missing. Its page references remain inherited and unverified; the new Cell Biology file is a different lecture.'};
write('docs/coverage.json',JSON.stringify({countingRule,counts:{lessonObjectives:points.length,distinctConcepts:uniquePointCount,scoredQuestions:questions.length,discussions:discussions.length},sourceStatus,knowledge:rows,sourcePages},null,2));
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Source coverage · LifeScience 11</title><link rel="stylesheet" href="../shared/course.css"><body class="course-home"><header class="course-bar"><a class="course-brand" href="../index.html">LifeScience 11</a><a href="../index.html#knowledge">Knowledge checklist</a></header><main><h1>Source coverage</h1><p>${esc(countingRule)}</p><div class="notice">${units.map(u=>`<strong>${esc(u.title)}:</strong> ${u.pointCount} objectives, ${u.questionCount} scored questions. ${esc(sourceStatus[u.id])}`).join('<br>')}</div><p>Every learning objective has a dedicated question. The combined test includes all ${questions.length} scored questions. The two ambiguous Levels image exercises on pages 38 and 50 remain unscored discussions.</p><h2>Learning objectives and assessments</h2><div class="table-scroll"><table class="coverage-table"><thead><tr><th>Lesson</th><th>Pages</th><th>Learning objective</th><th>Website location</th><th>Question IDs</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(units.find(u=>u.id===r.unit).title)}${r.sourceVerified?'':' · source unverified'}</td><td>${r.sourcePages}</td><td>${esc(r.title)}<br><small>${r.pointId}${r.canonical!==r.pointId?'<br>Shared concept: '+r.canonical:''}</small></td><td><a href="../${r.website}">Open lesson</a></td><td>${r.questions.map(id=>`<a href="../index.html#practice/question/${id}">${id}</a>`).join('<br>')}</td></tr>`).join('')}</tbody></table></div><h2>Cell Biology: all 43 pages</h2><div class="table-scroll"><table class="coverage-table"><thead><tr><th>PDF page</th><th>Learning objectives</th><th>Status / corrections</th></tr></thead><tbody>${sourcePages.filter(p=>p.unit==='biology').map(p=>`<tr><td><a href="../${p.website}">${p.page}</a></td><td>${p.points.join('<br>')||'Cover / agenda'}</td><td>${esc(p.status)}${p.clarifications.length?'<br>'+p.clarifications.map(c=>esc(c.text)).join('<br>'):''}</td></tr>`).join('')}</tbody></table></div><p><a href="coverage.json">Complete coverage data, including all source-page and question mappings</a></p></main></body></html>`;
write('docs/coverage.html',html);console.log(JSON.stringify({lessonObjectives:points.length,distinctConcepts:uniquePointCount,scoredQuestions:questions.length,discussions:discussions.length,units:units.map(({id,pointCount,questionCount})=>({id,pointCount,questionCount}))}));
