const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const base=path.resolve(__dirname,'..');
function data(files){const ctx={};ctx.window=ctx;vm.createContext(ctx);files.forEach(f=>vm.runInContext(fs.readFileSync(path.join(base,f),'utf8'),ctx));return ctx;}
function json(f){return JSON.parse(fs.readFileSync(path.join(base,f),'utf8').replace(/^\uFEFF/,''));}
const l=data(['units/levels/data.js','units/levels/learning.js']),c=data(['units/cells/data.js']).CELL_DATA;
const points=[...l.LEVELS.map(p=>({id:'levels-'+p.id,key:p.id,unit:'levels',title:p.en,pages:String(p.page),href:'units/levels/index.html#level-'+p.id,verified:true})),{id:'levels-hierarchy',key:'hierarchy',unit:'levels',title:'Structural hierarchy and relationships',pages:'1–9',href:'units/levels/index.html#hierarchy',verified:true},{id:'levels-life-processes',key:'life-processes',unit:'levels',title:'Life processes',pages:'6',href:'units/levels/index.html#life-processes',verified:true},...c.topics.flatMap(t=>t.facts.map(f=>({id:'cells-'+f.key,key:f.key,unit:'cells',title:f.en,pages:t.pages,href:'units/cells/index.html#fact-'+f.key,verified:false,topic:t.id})))];
const questions=[...json('data/levels-questions.json').map(q=>({...q,unit:'levels',points:['levels-'+q.pointKey]})),...json('data/cells-questions.json').map(q=>({...q,unit:'cells',points:['cells-'+q.pointKey]}))];
const conceptPoints={c1:['hierarchy'],c2:['organ'],c3:['cell'],c4:['system'],c5:['organism','population'],c6:['community'],c7:['ecosystem'],c8:['tissue','organ']};
l.CONCEPTS.forEach(q=>questions.push({id:'levels-original-'+q.id,unit:'levels',stem:q.en,options:q.options.map(o=>o[1]),answer:q.answer,explanation:q.explainEn,pages:q.page,points:conceptPoints[q.id].map(k=>'levels-'+k)}));
const discussions=[];
l.PHOTO_ITEMS.forEach(q=>{const level=l.LEVELS.find(p=>p.id===q.level);const row={id:'levels-photo-'+q.page,unit:'levels',stem:`Which level of organization does the highlighted subject represent? ${l.PHOTO_HINTS[q.page]?.[1]||'Classify the main subject in the image.'}`,image:'units/levels/images/'+q.image,imageAlt:'Classification exercise from source page '+q.page,options:l.LEVELS.slice(0,5).map(p=>p.en),answer:l.LEVELS.findIndex(p=>p.id===q.level),explanation:`${q.subjectEn}: ${level.en}. ${level.defEn} ${q.noteEn||''}`,pages:String(q.page),points:['levels-'+q.level]};([38,50].includes(q.page)?discussions:questions).push(row);});
const cellOldMap={1:['theory'],2:['prokaryote','eukaryote'],3:['membrane','cytoplasm','cytoskeleton'],4:['nucleus','nucleolus'],5:['ribosome','rough-er'],6:['smooth-er','golgi','vesicle'],7:['lysosome','vacuole'],8:['centrosome','cilia','flagella'],9:['mitochondria','chloroplast'],10:['comparison']};
c.questions.forEach(q=>{const ids=cellOldMap[q.id].map(k=>'cells-'+k);for(const id of ids)if(!points.some(p=>p.id===id))throw Error('Unknown mapped point '+id);questions.push({id:'cells-original-'+q.id,unit:'cells',stem:q.en,options:q.options.map(o=>o.en),answer:q.answer,explanation:q.explainEn,pages:c.topics.find(t=>t.id===q.id).pages,points:ids});});
const topics=['Levels of Organization','Cell Structure and Function','Cell Cycle: Mitosis and Meiosis','Photosynthesis and Cellular Respiration','Viruses','Evolution','Genetic Engineering','Asexual and Sexual Reproduction','Immunization and Vaccination'];
const units=[{id:'levels',title:'Levels of Organization Notes',topic:0,description:'Explore eight levels of life, from cells to ecosystems, with the original picture exercises.',href:'units/levels/index.html',image:'units/levels/images/page-12.jpg',pages:52,verified:true},{id:'cells',title:'Concept 1 · Cell Theory and Organelles',topic:1,description:'Explore animal and plant cells, connect structures with functions, and practise each learning objective.',href:'units/cells/index.html',image:'units/cells/assets/animal.png',pages:31,verified:false}];
for(const u of units){u.pointCount=points.filter(p=>p.unit===u.id).length;u.questionCount=questions.filter(q=>q.unit===u.id).length;}
const result={version:1,title:'LifeScience 11',topics,units,points,questions,discussions,uniquePointCount:points.length,countingRule:'One named learning objective per concept or fact card, with definitions, functions and examples grouped. The Levels unit has eight named levels plus hierarchy and life processes. The Cells unit has 27 fact cards in 10 groups. Related content across the units is cross-referenced; no complete objectives are equivalent, so all 37 remain after deduplication.'};
fs.writeFileSync(path.join(base,'course-data.js'),'window.COURSE_DATA='+JSON.stringify(result)+';\n');
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const rows=points.map(p=>({unit:p.unit,sourcePages:p.pages,pointId:p.id,title:p.title,website:p.href,questions:questions.filter(q=>q.points.includes(p.id)).map(q=>q.id),sourceVerified:p.verified}));
fs.writeFileSync(path.join(base,'docs','coverage.json'),JSON.stringify({countingRule:result.countingRule,sourceStatus:{levels:'Verified against supplied 52-page PDF, not an editable original PPT.',cells:'31-page source PDF/PPT missing; page references inherited from the existing website. Original source completeness cannot be verified.'},knowledge:rows,sourcePages:Array.from({length:52},(_,i)=>{let page=i+1;return{unit:'levels',page,points:page===1?['levels-hierarchy']:page<=9?['levels-'+l.LEVELS[page-2].id,...(page===6?['levels-life-processes']:[])]:['levels-'+l.PHOTO_ITEMS.find(p=>p.page===page).level],website:page===1?'units/levels/index.html#hierarchy':page<=9?points[page-2].href:'units/levels/index.html#photo-'+page,questions:page>=10?['levels-photo-'+page]:questions.filter(q=>q.unit==='levels'&&q.pages===String(page)).map(q=>q.id),status:[38,50].includes(page)?'Discussion; excluded from scoring':'Verified'}})},null,2));
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Source coverage · LifeScience 11</title><link rel="stylesheet" href="../shared/course.css"><body class="course-home"><header class="course-bar"><a class="course-brand" href="../index.html">LifeScience 11</a><a href="../index.html#knowledge">Knowledge checklist</a></header><main><h1>Source coverage</h1><p>${esc(result.countingRule)}</p><div class="notice"><strong>Levels:</strong> 52 supplied PDF pages checked, including 43 image exercises. 10 objectives, 59 scored questions and 2 unscored discussions.<br><strong>Cells:</strong> 27 objectives and 37 questions mapped to the existing website. The original 31-page PDF/PPT was not supplied; its page references and full content coverage remain unverified.</div><p>Every objective has a dedicated question. The combined test includes all 96 scored questions. Image pages 38 and 50 are ambiguous and stay in discussion practice. Each unit retains its original interactive learning pages.</p><div class="table-scroll"><table class="coverage-table"><thead><tr><th>Source</th><th>Pages</th><th>Knowledge objective</th><th>Website location</th><th>Question IDs</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.unit==='levels'?'Levels · verified PDF':'Cells · source unverified'}</td><td>${r.sourcePages}</td><td>${esc(r.title)}<br><small>${r.pointId}</small></td><td><a href="../${r.website}">Open lesson</a></td><td>${r.questions.map(id=>`<a href="../index.html#practice/question/${id}">${id}</a>`).join('<br>')}</td></tr>`).join('')}</tbody></table></div><p><a href="coverage.json">Detailed machine-readable coverage, including all 52 Levels pages</a></p></main></body></html>`;
fs.writeFileSync(path.join(base,'docs','coverage.html'),html);
console.log(JSON.stringify({points:points.length,scoredQuestions:questions.length,discussions:discussions.length,units}));
