const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');const root=path.resolve(__dirname,'..');const c={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'course-data.js'),'utf8'),c);const D=c.window.COURSE_DATA;
assert.equal(D.units.length,3);assert.equal(D.questions.filter(q=>q.unit!=='biology').length,96);assert.equal(D.discussions.length,2);assert.equal(new Set(D.questions.map(q=>q.id)).size,D.questions.length);assert.equal(D.uniquePointCount,new Set(D.points.map(p=>p.canonical)).size);
for(const p of D.points){assert(D.questions.some(q=>q.points.includes(p.id)),`No question: ${p.id}`);assert(fs.existsSync(path.join(root,p.href.split('#')[0])),`Missing lesson ${p.id}`);}
for(const q of D.questions){assert(q.stem&&q.explanation,`Missing copy ${q.id}`);assert(q.options.length>=3&&new Set(q.options).size===q.options.length,`Bad options ${q.id}`);assert(Number.isInteger(q.answer)&&q.answer>=0&&q.answer<q.options.length,`Bad answer ${q.id}`);assert(q.points.length>0,`No objective ${q.id}`);q.points.forEach(p=>assert(D.points.some(x=>x.id===p),`Bad point ${p} for ${q.id}`));if(q.image)assert(fs.existsSync(path.join(root,q.image)),`Missing image ${q.image}`);}
const Store=require('../shared/storage.js');const allRight=Object.fromEntries(D.questions.map(q=>[q.id,q.answer]));assert.equal(Store.grade(D.questions,allRight).correct,D.questions.length);const allWrong=Object.fromEntries(D.questions.map(q=>[q.id,(q.answer+1)%q.options.length]));assert.equal(Store.grade(D.questions,allWrong).correct,0);assert.equal(Store.grade(D.questions,{}).correct,0);const reversed=[...D.questions].reverse();assert.equal(Store.grade(reversed,allRight).correct,D.questions.length,'Shuffling must preserve answer mapping');
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.name.startsWith('.')||e.name==='qa-output'?[]:e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);}
for(const file of walk(root).filter(f=>f.endsWith('.html'))){const html=fs.readFileSync(file,'utf8');for(const match of html.matchAll(/(?:src|href)=["']([^"']+)["']/g)){let ref=match[1];if(/^(https?:|data:|#|mailto:)/.test(ref))continue;ref=ref.split(/[?#]/)[0];if(ref)assert(fs.existsSync(path.resolve(path.dirname(file),ref)),`Missing local reference ${ref} in ${file}`);}}
const B=JSON.parse(fs.readFileSync(path.join(root,'data/biology-objectives.json'),'utf8'));const source=JSON.parse(fs.readFileSync(path.join(root,'data/biology-source-pages.json'),'utf8'));assert.equal(source.length,43);for(let n=1;n<=43;n++){assert(fs.existsSync(path.join(root,'units/biology/pages/page-'+String(n).padStart(2,'0')+'.jpg')));if(n>=3)assert(B.some(o=>o.pages.includes(n)),'Unmapped biology page '+n);}for(const o of B)assert(o.questions.length>=1,'Untested biology objective '+o.key);
console.log(`PASS: ${D.points.length} lesson objectives (${D.uniquePointCount} distinct concepts), ${D.questions.length} scored questions, 2 discussions, all43 new source pages, scoring/order invariants, and static references.`);
