'use strict';
window.CYCLE_DATA={objectives:[
{key:'development',title:'From zygote to specialized cells',pages:[2,3],summary:'A fertilized egg divides repeatedly; cells then differentiate to build an organism.',bullets:['A zygote is the first cell formed after fertilization. Repeated cell division produces many cells.','Differentiation is the process by which cells become specialized in structure and function.','Specialized cells work together in tissues, organs and organ systems.'],zhTitle:'从合子到特化细胞',zhSummary:'受精卵反复分裂，细胞随后分化，逐步形成生物体。',zhBullets:['合子是受精后形成的第一个细胞。反复分裂会产生许多细胞。','细胞分化是细胞在结构和功能上变得特化的过程。','特化细胞共同组成组织、器官和器官系统。']},
{key:'stem-cells',title:'Stem cells and differentiation',pages:[4,5],summary:'Stem cells can produce one or more specialized cell types; their potential depends on their source and developmental state.',bullets:['Embryonic stem cells are undifferentiated and can develop into many cell types.','Adult stem cells occur in tissues such as bone marrow and can form a more limited set of related cell types.','Differentiation involves changes in which genes are active; mature specialization is usually stable.'],zhTitle:'干细胞与分化',zhSummary:'干细胞能够产生一种或多种特化细胞；其分化潜能取决于来源和发育阶段。',zhBullets:['胚胎干细胞尚未分化，可以发育成多种细胞类型。','骨髓等组织中有成体干细胞，可形成范围较有限、彼此相关的细胞类型。','分化涉及基因活性的改变；成熟细胞的特化通常较稳定。']},
{key:'cycle-purpose',title:'The cell cycle',pages:[6,10],summary:'The cell cycle is the repeating sequence of growth, DNA copying and cell division in eukaryotic cells.',bullets:['Cells divide for growth, replacement and repair.','The main parts are interphase, mitosis and cytokinesis.','Mitosis separates duplicated chromosomes; cytokinesis divides the cytoplasm into two daughter cells.'],zhTitle:'细胞周期',zhSummary:'细胞周期是真核细胞生长、复制 DNA 并分裂的重复过程。',zhBullets:['细胞分裂用于生长、细胞替换和修复。','主要阶段包括间期、有丝分裂和胞质分裂。','有丝分裂分开复制后的染色体；胞质分裂将细胞质分成两个子细胞。']},
{key:'interphase',title:'Interphase: G1, S and G2',pages:[7,10],summary:'During interphase, a cell grows, copies its DNA and prepares for division.',bullets:['G1: the cell grows and makes proteins and other materials.','S: DNA is replicated, so each chromosome is copied.','G2: growth continues and the cell makes materials needed for division.'],zhTitle:'间期：G1、S 和 G2',zhSummary:'间期中，细胞生长、复制 DNA，并为分裂做准备。',zhBullets:['G1：细胞生长，并制造蛋白质和其他物质。','S：DNA 复制，因此每条染色体都被复制。','G2：细胞继续生长，并制造分裂所需的物质。']},
{key:'chromosomes',title:'Chromosomes and chromatids',pages:[8,9],summary:'A replicated chromosome has two identical sister chromatids joined at a centromere.',bullets:['A chromosome is a long DNA molecule packaged with proteins; genes are sections of DNA.','After DNA replication, the two identical copies are sister chromatids joined at the centromere.','Telomeres protect chromosome ends. Human body cells usually have 46 chromosomes arranged in 23 pairs.'],zhTitle:'染色体与染色单体',zhSummary:'复制后的染色体由两条相同的姐妹染色单体组成，并在着丝粒处连接。',zhBullets:['染色体是与蛋白质包装在一起的长 DNA 分子；基因是 DNA 的片段。','DNA 复制后，两份相同的拷贝称为姐妹染色单体，并在着丝粒处连接。','端粒保护染色体末端。人体体细胞通常有 46 条染色体，组成 23 对。']},
{key:'mitosis-overview',title:'Mitosis: the sequence',pages:[11,12],summary:'Mitosis distributes one complete set of copied chromosomes to each of two nuclei.',bullets:['The sequence is prophase → metaphase → anaphase → telophase (PMAT).','Cytokinesis follows or overlaps late mitosis and physically separates the cell.','The result is usually two daughter cells with the same chromosome number and nearly identical DNA.'],zhTitle:'有丝分裂：阶段顺序',zhSummary:'有丝分裂将完整的复制染色体组分配给两个细胞核。',zhBullets:['阶段顺序是前期 → 中期 → 后期 → 末期（PMAT）。','胞质分裂随后发生，或与有丝分裂后期重叠，将细胞实际分开。','通常形成两个染色体数相同、DNA 几乎相同的子细胞。']},
{key:'prophase',title:'Prophase',pages:[12,13],summary:'Chromosomes condense and the mitotic spindle begins to form.',bullets:['Chromatin coils into visible chromosomes; each has two sister chromatids.','The nuclear envelope breaks down and spindle fibers form.','The source diagram shows centrioles in an animal cell; spindle organization varies among eukaryotes.'],zhTitle:'前期',zhSummary:'染色质凝缩成染色体，有丝分裂纺锤体开始形成。',zhBullets:['染色质盘绕成可见的染色体；每条染色体含两条姐妹染色单体。','核膜解体，纺锤丝形成。','原课件图展示的是带中心粒的动物细胞；不同真核生物组织纺锤体的方式有所不同。']},
{key:'metaphase',title:'Metaphase',pages:[12,14],summary:'Duplicated chromosomes line up across the middle of the cell.',bullets:['Spindle microtubules attach to chromosome regions at the centromere/kinetochore.','Chromosomes align at the cell equator.','This arrangement helps each future nucleus receive one copy of every chromosome.'],zhTitle:'中期',zhSummary:'复制后的染色体排列在细胞中央。',zhBullets:['纺锤体微管连接到染色体着丝粒区域的动粒。','染色体排列在细胞赤道面。','这种排列有助于确保未来的每个细胞核都获得每条染色体的一份拷贝。']},
{key:'anaphase',title:'Anaphase',pages:[12,15],summary:'Sister chromatids separate and move toward opposite ends of the cell.',bullets:['Once separated, each former chromatid is counted as an individual chromosome.','Spindle microtubules move the chromosome copies toward opposite poles.','This is the key separation step that gives each side a matching set.'],zhTitle:'后期',zhSummary:'姐妹染色单体分开，移向细胞两端。',zhBullets:['分开后，每条原姐妹染色单体都算作一条独立染色体。','纺锤体微管将染色体拷贝移向细胞相对两极。','这是确保两侧各获得一套相同染色体的关键分离步骤。']},
{key:'telophase',title:'Telophase',pages:[12,16],summary:'Two new nuclear envelopes form as chromosomes begin to relax.',bullets:['A nuclear envelope forms around each chromosome set.','Chromosomes decondense toward chromatin.','The spindle disassembles and cytokinesis begins.'],zhTitle:'末期',zhSummary:'新的核膜分别形成，染色体开始松散。',zhBullets:['每套染色体周围形成新的核膜。','染色体去凝缩，恢复为染色质状态。','纺锤体解体，胞质分裂开始。']},
{key:'cytokinesis',title:'Cytokinesis in animal and plant cells',pages:[12,17],summary:'Cytokinesis divides the cytoplasm and completes separation into daughter cells.',bullets:['In animal cells, a cleavage furrow pinches the membrane inward.','In plant cells, a cell plate forms between the nuclei and develops into new separating membranes and wall.','Mitosis divides the nucleus; cytokinesis divides the cytoplasm.'],zhTitle:'动物细胞与植物细胞的胞质分裂',zhSummary:'胞质分裂将细胞质分开，完成子细胞的分离。',zhBullets:['动物细胞形成分裂沟，细胞膜向内收缩。','植物细胞在细胞核之间形成细胞板，并逐渐发育成新的分隔膜和细胞壁。','有丝分裂分开细胞核；胞质分裂分开细胞质。']},
{key:'division-rates',title:'Cell division, growth and repair',pages:[18],summary:'Different tissues replace cells at different rates; cell division supports growth and repair.',bullets:['The lecture compares intestinal lining (about 5 days), skin (about 2 weeks), red blood cells (about 4 months) and liver cells (about 1 year). These are approximate examples, not universal timers.','Cells divide to replace lost or damaged cells and to support growth.','As a similarly shaped cell gets larger, volume grows faster than surface area, making exchange across the membrane more demanding.'],zhTitle:'细胞分裂、生长与修复',zhSummary:'不同组织更新细胞的速度不同；细胞分裂支持生长和修复。',zhBullets:['课件举例比较：肠道内壁约 5 天、皮肤约 2 周、红细胞约 4 个月、肝细胞约 1 年。这些是近似示例，并非适用于所有人的固定计时。','细胞分裂可替换丢失或受损细胞，并支持生长。','形状相似的细胞越大，体积增长越快于表面积，跨膜物质交换的负担也随之增加。']},
{key:'cycle-regulation',title:'Cell-cycle regulation and checkpoints',pages:[20,21],summary:'Internal and external signals help cells decide whether to continue, pause or stop the cycle.',bullets:['External signals include growth factors, hormones and nutrient availability; internal signals report the cell’s condition and DNA status.','Checkpoints assess whether key events are complete and conditions are suitable before the cycle proceeds.','Signals are context-dependent: animal cells may need growth signals, but division is not simply “off” in every healthy cell.'],zhTitle:'细胞周期调控与检查点',zhSummary:'内部和外部信号帮助细胞决定继续、暂停或停止周期。',zhBullets:['外部信号包括生长因子、激素和营养物质；内部信号反映细胞状态和 DNA 情况。','检查点会评估关键事件是否完成、条件是否合适，再决定周期是否继续。','信号作用取决于情境：动物细胞可能需要生长信号，但不能简化为所有健康细胞的分裂都处于“关闭”状态。']},
{key:'apoptosis',title:'Apoptosis: programmed cell death',pages:[22],summary:'Apoptosis is a regulated process that removes cells when they are no longer needed or are damaged.',bullets:['Cell signals activate an orderly self-destruction program; the cell is dismantled and its components can be cleared.','Apoptosis helps shape developing tissues, including the separation of fingers and toes.','It is a normal part of tissue maintenance, not the same as accidental cell injury.'],zhTitle:'细胞凋亡：程序性细胞死亡',zhSummary:'细胞凋亡是一种受调控的过程，可清除不再需要或受损的细胞。',zhBullets:['细胞信号会启动有序的自我解体程序；细胞被拆解，其成分可被清除。','细胞凋亡帮助塑造发育中的组织，例如手指和脚趾之间的分离。','细胞凋亡是组织维护的正常部分，与意外损伤不同。']},
{key:'cancer',title:'Cancer and tumors',pages:[23],summary:'Cancer develops when cells acquire changes that disrupt normal controls on growth and survival.',bullets:['Cancer cells can keep dividing when normal cells would pause, repair damage or die.','Some cancers form solid tumors; not every cancer does.','Cancer development usually involves multiple changes over time, rather than one simple event.'],zhTitle:'癌症与肿瘤',zhSummary:'当细胞发生改变并破坏正常的生长与存活调控时，可能发展为癌症。',zhBullets:['正常细胞会暂停、修复损伤或死亡时，癌细胞可能仍继续分裂。','有些癌症会形成实体瘤，但并非所有癌症都会形成实体瘤。','癌症通常涉及多个变化逐渐累积，而非单一简单事件。']},
{key:'tumors',title:'Benign and malignant tumors',pages:[23,24],summary:'Benign and malignant tumors differ in their ability to invade nearby tissue and spread.',bullets:['Benign tumors do not invade nearby tissue or metastasize, although their size or location can still cause health problems.','Malignant tumors can invade surrounding tissue; cancer cells may spread to distant sites and form secondary tumors.','Metastasis means cancer has spread from its original site to another part of the body.'],zhTitle:'良性与恶性肿瘤',zhSummary:'良性和恶性肿瘤的区别之一，是它们侵入周围组织和扩散的能力。',zhBullets:['良性肿瘤不会侵入邻近组织或发生转移，但其大小或位置仍可能造成健康问题。','恶性肿瘤可侵入周围组织；癌细胞也可能扩散到远处并形成继发肿瘤。','转移是指癌症从原发部位扩散到身体其他部位。']},
{key:'cancer-causes',title:'DNA changes and cancer risk',pages:[25],summary:'Cancer risk can rise when DNA changes affect genes that control cell growth; causes vary.',bullets:['DNA changes can happen during cell division, be inherited, or result from exposures such as tobacco smoke, ultraviolet radiation and ionizing radiation such as X-rays.','Some infections, including certain types of HPV, can raise the risk of particular cancers; cancer itself is not contagious.','A carcinogen is an agent that can contribute to cancer. Exposure does not mean a person will certainly develop cancer.'],zhTitle:'DNA 改变与癌症风险',zhSummary:'影响细胞生长调控基因的 DNA 改变可能增加癌症风险；原因因人而异。',zhBullets:['DNA 改变可能发生在细胞分裂过程中、遗传而来，或由烟草烟雾、紫外线及 X 射线等电离辐射暴露造成。','某些感染（包括部分 HPV 类型）会提高特定癌症的风险；癌症本身不会传染。','致癌物是可能促成癌症的因素。接触致癌物并不表示一定会患癌。']}
]};
